function enhanceAccountPolicy(html,path){
  if(!html)return html;
  if(path==='/privacy/'){
    html=html.replace('Australian Product Guide is designed to minimise personal information collection. The current public site does not require an account, payment profile, newsletter signup or contact form to search, compare or use recommendation tools.','Australian Product Guide is designed to minimise personal information collection. Search, comparison and recommendation tools remain available without an account. An optional My APG account can be used to sync selected workspace data across devices.');
    html=html.replace('<h2 id="not-collected">3. Information APG does not currently ask you to provide</h2><p>The application currently has no consumer account registration, checkout, payment card capture, newsletter signup or public free-text contact form.</p>','<h2 id="account">3. Optional My APG accounts</h2><p>If you choose to create a My APG account, APG processes your email address, authentication records and the workspace items you choose to sync. Authentication and synced workspace data are provided through APG\'s Supabase project hosted in the Sydney region. Account data is not used to change product suitability scores or affiliate rankings.</p><h2 id="not-collected">4. Information APG does not ask you to provide</h2><p>APG does not operate checkout, payment-card capture, newsletter signup or a public free-text contact form. An account is optional and is not required to browse, search, compare or use Decision Lab.</p>');
    html=html.replace('<h2 id="local">4. Browser local storage</h2>','<h2 id="local">5. Browser local storage and sync</h2>');
    html=html.replace('They are not an APG cloud account.','If you remain signed out, they stay browser-local. If you sign in and request sync, selected workspace records are copied to your APG account so they can be available on another signed-in device.');
    html=html.replace('<h2 id="cookies">5. Cookies and analytics</h2>','<h2 id="cookies">6. Cookies and analytics</h2>');
    html=html.replace('The current APG application code does not include a first-party behavioural analytics or advertising-pixel implementation. Hosting, security infrastructure and third-party services may process technical data required to operate their services. If APG later introduces analytics or advertising technology, this policy and any consent/notice controls will need to be reviewed before activation.','APG does not use an advertising pixel or cross-site tracking cookie. The application samples browser performance measurements such as Largest Contentful Paint, Cumulative Layout Shift, Interaction to Next Paint, First Contentful Paint and Time to First Byte. The payload contains the page path, broad viewport class and navigation type, but no query string, account identifier or persistent analytics identifier. These measurements are sent to APG\'s own endpoint and recorded in hosting logs for performance diagnosis. Hosting, security infrastructure and third-party services may also process technical data required to operate their services.');
    html=html.replace('<h2 id="technical">6. Technical and usage information</h2>','<h2 id="technical">7. Technical and usage information</h2>');
    html=html.replace('<h2 id="search">7. Search, comparison and recent activity</h2><p>Recent searches, comparison selections and recent/saved products are currently implemented through browser local storage. APG\'s application does not currently sync these into a user account.</p>','<h2 id="search">8. Search, comparison and recent activity</h2><p>Recent searches, comparison selections, recent/saved products, Decision Lab history, saved comparisons and guides are stored locally by default. If you create an account and sync, those selected workspace records can also be stored against your authenticated user ID.</p>');
    html=html.replace('<h2 id="affiliate">8. Affiliate click-outs and retailer relationships</h2>','<h2 id="affiliate">9. Affiliate click-outs and retailer relationships</h2>');
    html=html.replace('<h2 id="third-party">9. Third-party services and disclosure</h2>','<h2 id="third-party">10. Third-party services and disclosure</h2>');
    html=html.replace('<h2 id="overseas">10. Overseas processing</h2>','<h2 id="overseas">11. Overseas processing</h2>');
    html=html.replace('<h2 id="retention">11. Retention</h2><p>Device-local APG convenience data remains until it is cleared or overwritten in the browser. Infrastructure logs are governed by the relevant provider configuration and operational need. APG should adopt explicit retention rules before collecting material identifiable user data.</p>','<h2 id="retention">12. Retention and deletion</h2><p>Device-local APG convenience data remains until it is cleared or overwritten in the browser. Synced workspace data remains while the account exists or until the relevant records are replaced or deleted. My APG includes a self-service Delete account action that deletes the authenticated Supabase user and cascades deletion of synced APG workspace data. Performance measurements are retained only within applicable hosting-log retention and are not linked by APG to an account ID. Infrastructure logs remain subject to provider configuration and operational need.</p>');
    html=html.replace('<h2 id="security">12. Security</h2>','<h2 id="security">13. Security</h2>');
    html=html.replace('<h2 id="rights">13. Access, correction and complaints</h2><p>Because APG does not currently operate user accounts or a public personal-data submission form, it holds limited user-provided information in its own application. A dedicated business privacy contact and documented access/correction/complaint process should be activated before identifiable personal information is collected at material scale.</p>','<h2 id="rights">14. Access, correction and complaints</h2><p>Signed-in users can inspect and manage the APG workspace associated with their account and can delete the account from My APG. A dedicated venture privacy contact and documented access/correction/complaint process should be activated as identifiable information collection grows.</p>');
    html=html.replace('<h2 id="act">14. Australian Privacy Act position</h2>','<h2 id="act">15. Australian Privacy Act position</h2>');
    html=html.replace('<h2 id="updates">15. Policy updates</h2>','<h2 id="updates">16. Policy updates</h2>');
    html=html.replace('<h2 id="contact">16. Contact</h2>','<h2 id="contact">17. Contact</h2>');
  }
  if(path==='/terms/'){
    html=html.replace('<h2 id="acceptable">11. Acceptable use</h2>','<h2 id="accounts">11. Optional accounts</h2><p>My APG accounts are optional. You are responsible for keeping your sign-in credentials secure. APG may restrict or discontinue account functionality where reasonably necessary for security, abuse prevention or service operation. Deleting an account removes the authenticated account and synced APG workspace records, while browser-local data remains until separately cleared.</p><h2 id="acceptable">12. Acceptable use</h2>');
    html=html.replace('<h2 id="reliance">12. Reliance and risk</h2>','<h2 id="reliance">13. Reliance and risk</h2>');
    html=html.replace('<h2 id="liability">13. Liability and mandatory rights</h2>','<h2 id="liability">14. Liability and mandatory rights</h2>');
    html=html.replace('<h2 id="service">14. Changes to the service</h2>','<h2 id="service">15. Changes to the service</h2>');
    html=html.replace('<h2 id="updates">15. Changes to these terms</h2>','<h2 id="updates">16. Changes to these terms</h2>');
    html=html.replace('<h2 id="law">16. Governing law</h2>','<h2 id="law">17. Governing law</h2>');
    html=html.replace('<h2 id="contact">17. Contact</h2>','<h2 id="contact">18. Contact</h2>');
  }
  return html;
}
module.exports={enhanceAccountPolicy};