// APG authority depth v14: surfaces deep Australian evidence without changing the lightweight SSR architecture.
const data=require('../data');
const app=require('./semantic-scout-fix-v13');
const ASSET='/assets/authority-v14.css';
const authoritySlugs=new Set(['coffee-grinders','home-printers','pizza-ovens']);
const css=`
[data-authority-category] .product-visual .category-icon svg{display:none!important}
[data-authority-category] .product-visual .category-icon:before{display:grid;place-items:center;min-width:54px;height:42px;padding:0 7px;border:2px solid currentColor;border-radius:8px;font-size:10px;font-weight:900;letter-spacing:.055em}
[data-authority-category="coffee-grinders"] .product-visual .category-icon:before{content:"GRIND"}
[data-authority-category="home-printers"] .product-visual .category-icon:before{content:"PRINT"}
[data-authority-category="pizza-ovens"] .product-visual .category-icon:before{content:"PIZZA"}
.apg-authority-band{margin:28px auto;padding:22px;border:1px solid #cfe0dc;border-radius:18px;background:linear-gradient(135deg,#f4faf8,#fff)}
.apg-authority-band .apg-authority-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:20px;align-items:start}.apg-authority-band h2{margin:.25rem 0 .55rem}.apg-authority-band p{color:#4d6670;line-height:1.6}.apg-authority-badge{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border-radius:999px;background:#e3f3ee;color:#076d67;font-size:11px;font-weight:850;white-space:nowrap}.apg-authority-factors{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:16px}.apg-authority-factor{padding:14px;border:1px solid #dce7e4;border-radius:13px;background:#fff}.apg-authority-factor span{display:block;color:#08766f;font-size:10px;font-weight:900;letter-spacing:.08em}.apg-authority-factor strong{display:block;margin-top:7px;font-size:13px;line-height:1.4;color:#102f3f}
.apg-authority-specs{padding:54px 0;background:#f5f8f7;border-block:1px solid #e0e8e6}.apg-authority-specs .section-head{margin-bottom:22px}.apg-authority-spec-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.apg-authority-spec{padding:16px;border:1px solid #d7e3e0;border-radius:14px;background:#fff}.apg-authority-spec dt{font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.07em;color:#60757c}.apg-authority-spec dd{margin:7px 0 0;font-size:14px;font-weight:750;line-height:1.4;color:#102f3f}
.apg-authority-commerce{margin:28px 0;padding:20px;border:1px solid #d5e3df;border-radius:17px;background:#fff}.apg-authority-commerce h2{margin:.2rem 0 .5rem}.apg-authority-commerce>p{color:#526b73}.apg-authority-links{display:grid;gap:9px;margin-top:14px}.apg-authority-link{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:12px;align-items:center;padding:12px;border:1px solid #dde8e5;border-radius:13px;text-decoration:none;color:#102f3f;background:#fbfdfc}.apg-authority-link:hover{border-color:#97bdb6;background:#f3f9f7}.apg-authority-mark{width:40px;height:40px;display:grid;place-items:center;border-radius:10px;background:#e8f4f0;color:#08766f;font-size:11px;font-weight:900}.apg-authority-link strong{font-size:13px}.apg-authority-link small{display:block;margin-top:3px;color:#5a7078;font-size:10.5px;line-height:1.45}.apg-authority-link b{font-size:11px;color:#087069;white-space:nowrap}
.apg-authority-related{margin:32px auto}.apg-authority-related-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;margin-top:14px}.apg-authority-related a{display:flex;min-height:82px;align-items:center;padding:14px;border:1px solid #dce6e4;border-radius:13px;background:#fff;color:#102f3f;text-decoration:none;font-weight:800;font-size:12px;line-height:1.35}.apg-authority-related a:hover{border-color:#91b8b1;background:#f3f9f7}
.apg-image-status{margin-top:12px;padding:12px 14px;border-left:3px solid #e7ad4d;background:#fff9ed;color:#5b5140;font-size:11px;line-height:1.5}
@media(max-width:900px){.apg-authority-factors{grid-template-columns:repeat(2,minmax(0,1fr))}.apg-authority-spec-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.apg-authority-related-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:640px){.apg-authority-band .apg-authority-head{grid-template-columns:1fr}.apg-authority-badge{white-space:normal}.apg-authority-factors,.apg-authority-spec-grid,.apg-authority-related-grid{grid-template-columns:1fr}.apg-authority-link{grid-template-columns:40px minmax(0,1fr)}.apg-authority-link b{grid-column:2}}
`;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pathOf(req){try{return new URL(req.url,'https://australianproductguide.au').pathname}catch{return '/';}}
function categoryFromPath(path){let m=path.match(/^\/categories\/([^/]+)\//);if(m&&authoritySlugs.has(m[1]))return data.categories[m[1]];m=path.match(/^\/guides\/([^/]+)-buying-guide\/$/);if(m&&authoritySlugs.has(m[1]))return data.categories[m[1]];m=path.match(/^\/compare\/([^/]+)\//);if(m&&authoritySlugs.has(m[1]))return data.categories[m[1]];return null;}
function productFromPath(path){const m=path.match(/^\/products\/([^/]+)\/$/);if(!m)return null;const p=data.products.find(x=>x.slug===m[1]);return p&&authoritySlugs.has(p.category)?p:null;}
function authorityBand(c){return `<section class="wrap apg-authority-band" aria-label="APG authority evidence standard"><div class="apg-authority-head"><div><p class="kicker">Deep Australian evidence</p><h2>Exact models, documented trade-offs and separately verified buying pathways.</h2><p>${esc(c.authorityIntro||c.description)}</p></div><span class="apg-authority-badge">✓ Manufacturer-verified · checked 17 Aug 2026</span></div><div class="apg-authority-factors">${c.factors.map((f,i)=>`<div class="apg-authority-factor"><span>DECISION ${String(i+1).padStart(2,'0')}</span><strong>${esc(f)}</strong></div>`).join('')}</div></section>`;}
function relatedBlock(c){const rows=(c.relatedCategories||[]).map(s=>data.categories[s]).filter(Boolean);if(!rows.length)return '';return `<section class="wrap apg-authority-related"><p class="kicker">Continue the buying journey</p><h2>Related Australian product decisions</h2><p>Curated by decision context rather than alphabetical proximity or affiliate availability.</p><div class="apg-authority-related-grid">${rows.map(x=>`<a href="/categories/${x.slug}/">${esc(x.label)} →</a>`).join('')}</div></section>`;}
function specsBlock(p){const rows=(p.specs||[]);if(!rows.length)return '';return `<section class="apg-authority-specs"><div class="wrap"><div class="section-head"><div><p class="kicker">Verified model specifications</p><h2>Exact Australian product facts that can change the decision</h2><p>Manufacturer specifications checked 17 Aug 2026. APG separates documented facts from suitability judgements.</p></div><span class="apg-authority-badge">Deep evidence</span></div><dl class="apg-authority-spec-grid">${rows.map(([k,v])=>`<div class="apg-authority-spec"><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></div></section>`;}
function commerceBlock(p){const retailers=p.verifiedRetailers||[],sources=p.evidenceSources||[];if(!retailers.length&&!sources.length)return '';const retailerLinks=retailers.map(r=>`<a class="apg-authority-link" href="${esc(r.url)}" rel="nofollow noopener" target="_blank"><span class="apg-authority-mark">AU</span><span><strong>${esc(r.retailer)}</strong><small>${esc(r.note||'Exact Australian product pathway verified 17 Aug 2026.')}</small></span><b>Open ↗</b></a>`).join('');const sourceLinks=sources.map(r=>`<a class="apg-authority-link" href="${esc(r.url)}" rel="noopener" target="_blank"><span class="apg-authority-mark">SRC</span><span><strong>${esc(r.label)}</strong><small>Supporting primary evidence · non-affiliate</small></span><b>Open ↗</b></a>`).join('');return `<section class="apg-authority-commerce"><p class="kicker">Verified Australian pathways</p><h2>Retailers and supporting evidence, kept separate from product fit</h2><p>These exact-model links were checked on 17 Aug 2026. Stock, seller and price can change after verification. Retailer availability contributes zero recommendation points.</p><div class="apg-authority-links">${retailerLinks}${sourceLinks}</div><div class="apg-image-status"><strong>Product photography status:</strong> APG is deliberately not publishing third-party product photography for this model until an authorised image delivery source or explicit reusable rights are verified. No imagery has been scraped or fabricated.</div></section>`;}
function injectCategory(html,c){let out=html.replace(/Reviewed 15 Aug 2026/g,'Reviewed 17 Aug 2026').replace(/Reviewed 15\/08\/2026/g,'Reviewed 17/08/2026');if(!out.includes('apg-authority-band')){const marker='<section class="section"><div class="section-head"><div><p class="kicker">Decision shortcuts</p>';out=out.includes(marker)?out.replace(marker,authorityBand(c)+marker):out.replace('</main>',authorityBand(c)+'</main>');}if(!out.includes('apg-authority-related'))out=out.replace('</main>',relatedBlock(c)+'</main>');return out;}
function injectProduct(html,p){let out=html.replace(/Reviewed 15 Aug 2026/g,'Reviewed 17 Aug 2026').replace(/Reviewed 15\/08\/2026/g,'Reviewed 17/08/2026');const generic=/<section class="section soft-section full-bleed">[\s\S]*?<\/section>/;if((p.specs||[]).length)out=generic.test(out)?out.replace(generic,specsBlock(p)):out.replace('</main>',specsBlock(p)+'</main>');if(!out.includes('apg-authority-commerce')){const marker='<aside class="evidence-box">';out=out.includes(marker)?out.replace(marker,commerceBlock(p)+marker):out.replace('</main>',commerceBlock(p)+'</main>');}return out;}
function addBodyCategory(html,slug){return html.replace('<body ','<body data-authority-category="'+esc(slug)+'" ');}
function send(req,res){res.statusCode=200;res.setHeader('Content-Type','text/css; charset=utf-8');res.setHeader('Cache-Control','public, max-age=3600');res.setHeader('X-Content-Type-Options','nosniff');return res.end(req.method==='HEAD'?'':css);}
module.exports=(req,res)=>{const path=pathOf(req);if(path===ASSET)return send(req,res);const c=categoryFromPath(path),p=productFromPath(path),active=p?data.categories[p.category]:c;const end=res.end.bind(res);res.end=(body,...args)=>{const type=String(res.getHeader('Content-Type')||'').toLowerCase();if(req.method!=='HEAD'&&res.statusCode===200&&typeof body==='string'&&type.startsWith('text/html')&&active){body=body.replace('</head>',`<link rel="stylesheet" href="${ASSET}"></head>`);body=addBodyCategory(body,active.slug);body=p?injectProduct(body,p):injectCategory(body,active);}return end(body,...args);};return app(req,res);};
