const {categories}=require('../data');
const {esc,layout,hero,retailerButton}=require('./ui');
const coffee=categories['coffee-machines'];
const max=110;
function workflowScore(pref,p){if(pref===p.workflow)return {score:20,penalty:0};if(pref==='guided'||p.workflow==='guided')return {score:10,penalty:0};return {score:0,penalty:-35};}
function drinkScore(pref,p){if(pref==='black')return 20;if(pref==='milk')return p.milk==='automatic'?20:p.milk==='handsfree'?18:13;if(pref==='mixed')return p.breadth==='broad'?20:p.breadth==='moderate'?16:14;if(pref==='cold')return p.cold?20:0;return 0;}
function learningScore(pref,p){const m={almost:{low:20,medium:12,high:4},some:{low:15,medium:20,high:12},control:{low:5,medium:14,high:20}};return m[pref]?.[p.learning]??0;}
function budgetScore(ceiling,p){if(!ceiling)return {score:0,eligible:false};if(p.price<=ceiling*.8)return {score:20,eligible:true};if(p.price<=ceiling)return {score:18,eligible:true};if(p.price<=ceiling*1.1)return {score:8,eligible:true};return {score:0,eligible:false};}
function speedScore(pref,p){if(pref==='low')return 10;if(pref==='high')return ({5:15,4:12,3:8,2:4,1:0})[p.convenience]??0;return ({5:12,4:14,3:15,2:12,1:8})[p.convenience]??0;}
function spaceScore(pref,p){if(pref==='any')return {score:10,eligible:true};if(pref==='compact'){if(p.depth>450||p.width>300)return {score:0,eligible:false};return {score:p.width<=260?10:7,eligible:true};}return {score:(p.width<=430&&p.depth<=450)?10:0,eligible:p.width<=430&&p.depth<=450};}
function beanScore(pref,p){if(pref==='rarely')return 5;if(pref==='sometimes')return p.beanSwitch?5:3;return p.beanSwitch?5:1;}
function score(p,q){const w=workflowScore(q.workflow,p),b=budgetScore(Number(q.budget),p),s=spaceScore(q.space,p);if(!b.eligible||!s.eligible)return {...p,eligible:false,score:0};const raw=w.score+drinkScore(q.drink,p)+learningScore(q.learning,p)+b.score+speedScore(q.speed,p)+s.score+beanScore(q.beans,p)+w.penalty;return {...p,eligible:true,score:Math.round(Math.max(0,raw)/max*1000)/10};}
const select=(name,label,options,value)=>`<label for="${name}">${esc(label)}</label><select id="${name}" name="${name}" required><option value="">Choose</option>${options.map(([v,l])=>`<option value="${v}"${value===v?' selected':''}>${esc(l)}</option>`).join('')}</select>`;
function render(req,u){const q={workflow:u.searchParams.get('workflow')||'',drink:u.searchParams.get('drink')||'',learning:u.searchParams.get('learning')||'',budget:u.searchParams.get('budget')||'',speed:u.searchParams.get('speed')||'',space:u.searchParams.get('space')||'',beans:u.searchParams.get('beans')||''};const complete=Object.values(q).every(Boolean);let result='';if(complete){const ranked=coffee.products.map(p=>score(p,q)).filter(p=>p.eligible).sort((a,b)=>b.score-a.score||a.price-b.price);if(ranked.length){const best=ranked[0],close=ranked.slice(1).filter(p=>best.score-p.score<=3);result=`<div class="result"><p class="eyebrow">Best fit · ${best.score.toFixed(1)}/100</p><h2><a href="/products/${best.slug}/">${esc(best.name)}</a></h2><p>${esc(best.summary)}</p>${close.length?`<p><strong>Close call${close.length>1?'s':''}:</strong> ${close.map(p=>`<a href="/products/${p.slug}/">${esc(p.name)} ${p.score.toFixed(1)}</a>`).join('; ')}</p>`:''}<p>This result uses the documented 110-point suitability model with hard budget and space gates. Affiliate relationships contribute zero points.</p>${retailerButton(best)}</div><h2>Next alternatives</h2><div class="grid">${ranked.slice(1,4).map(p=>`<article class="card"><p class="eyebrow">${p.score.toFixed(1)}/100</p><h3><a href="/products/${p.slug}/">${esc(p.name)}</a></h3><p>${esc(p.summary)}</p></article>`).join('')}</div>`:`<div class="notice"><strong>No eligible product matched the hard budget and space gates.</strong> Adjust those constraints to see alternatives.</div>`;}}
const form=`<form class="finder" method="get">${select('workflow','How hands-on do you want your coffee routine to be?',[['one-touch','One-touch'],['guided','Guided but hands-on'],['manual','Manual and hands-on']],q.workflow)}${select('drink','What do you usually drink?',[['black','Mostly black'],['milk','Mostly milk-based'],['mixed','Mixed household'],['cold','Cold coffee matters']],q.drink)}${select('learning','How much learning and technique are you happy with?',[['almost','Almost none'],['some','Some guidance'],['control','Control and skill-building']],q.learning)}${select('budget','What is your comfortable machine budget?',[['700','Under A$700'],['1000','A$700–1,000'],['1500','A$1,000–1,500'],['2000','A$1,500–2,000'],['99999','A$2,000+']],q.budget)}${select('speed','How important is speed and convenience on busy mornings?',[['low','Low'],['medium','Medium'],['high','High']],q.speed)}${select('space','How much bench space can you spare?',[['compact','Compact only'],['normal','Normal appliance space'],['any','Space not a concern']],q.space)}${select('beans','Do you like changing between different beans?',[['rarely','Rarely'],['sometimes','Sometimes'],['often','Often']],q.beans)}<button class="button" type="submit">Show my best fit</button></form>`;
const body=hero('Help Me Choose','Find your coffee-machine fit','Answer seven practical questions. The matcher applies the same deterministic scoring and hard-stop rules used in the verified coffee QA profiles.')+form+result+`<section><h2>How the matcher works</h2><p>The model scores workflow fit, drink needs, learning appetite, budget, morning convenience, bench space and bean switching. Products more than 10% over your budget ceiling or outside a compact-space hard stop cannot be Best Fit. Commercial relationships contribute zero points.</p><p><a href="/methodology/">Read the full methodology</a> or <a href="/compare/coffee-machines/">compare all maintained coffee machines</a>.</p></section>`;return layout(req,{title:'Help Me Choose a Coffee Machine | Australian Product Guide',description:'Seven-question deterministic coffee-machine matcher using maintained Australian product evidence.',path:'/categories/coffee-machines/finder/',body,crumbs:[{name:'Home',path:'/'},{name:'Coffee machines',path:'/categories/coffee-machines/'},{name:'Help Me Choose',path:'/categories/coffee-machines/finder/'}]});}
module.exports={render,score};
