const {products,categories}=require('../data');
const {slugify}=require('./routes');
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9$]+/g,' ').trim();
const human=s=>String(s||'').replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const words=s=>norm(s).split(/\s+/).filter(Boolean);
const STOP=new Set(['a','an','and','best','buy','for','good','i','in','is','me','my','of','or','please','the','to','want','with','under','below','less','than','up','max','maximum']);
const CATEGORY_ALIASES=Object.fromEntries(Object.values(categories).map(c=>[c.slug,[...new Set([c.label,c.label.replace(/s$/,''),c.slug.replace(/-/g,' '),...(c.aliases||[])])]]));
const TAG_ALIASES={
  value:['value','budget','affordable','cheap','lower price','price conscious'],premium:['premium','flagship','high end','top tier'],beginner:['beginner','easy','simple','low effort'],'hands-on':['hands on','manual control','manual workflow'],
  milk:['milk','latte','flat white','cappuccino'],cold:['cold','iced','cold brew','cold coffee'],compact:['compact','small','small kitchen','small space','apartment','narrow'],family:['family','family of 4','large household'],
  'dual-zone':['dual','dual zone','two basket','2 basket','two drawer'],'versatile':['versatile','multi function','multifunction','steam','grill'],quiet:['quiet','silent','low noise'],mopping:['mop','mopping','vacuum and mop'],pets:['pet','pets','pet hair','dog hair','cat hair'],
  'low-maintenance':['low maintenance','automatic dock','omni station','hands off cleaning'],obstacle:['obstacle','avoidance','navigation'],anc:['anc','noise cancellation','noise cancelling','noise canceling'],battery:['battery','long battery','battery life'],travel:['travel','flight','flying','plane','commute','commuting'],apple:['apple','iphone','ipad','mac','apple ecosystem'],bass:['bass','bass heavy'],
  outdoor:['outdoor','outside','weatherproof'],battery:['battery','battery powered','wireless battery'],solar:['solar','solar powered'], 'local-storage':['local storage','microsd','micro sd','no subscription'],subscription:['subscription','cloud plan'],
  'wifi-7':['wifi 7','wi fi 7','wi-fi 7'],ethernet:['ethernet','wired backhaul'],portable:['portable','travel size'], 'carry-on':['carry on','carry-on','cabin bag'],lightweight:['lightweight','light weight','easy to carry'],
  'fast-charge':['fast charge','fast charging','quick charge'], 'high-output':['high output','high power'], 'usb-c':['usb c','usb-c','type c'], '4k':['4k','uhd'],qhd:['qhd','1440p'],creator:['creator','photo editing','video editing'],
  ergonomic:['ergonomic','ergonomics'],lumbar:['lumbar','back support'],smart:['smart','app control','wifi control'],rfid:['rfid','microchip'], 'dual-motor':['dual motor','two motor'],wireless:['wireless','bluetooth'],gaming:['gaming','gamer','esports'],
  cardio:['cardio','running','cycling','rowing'],strength:['strength','weights','dumbbell'],hepa:['hepa','allergy','allergies','pollen'],hammer:['hammer drill','masonry'],trade:['trade','professional'],package:['package','parcel'],offline:['offline','no wifi','without wifi'],app:['app','phone app'],
  gps:['gps','running','outdoor fitness'], 'subscription-free':['no subscription','subscription free'],waterproof:['waterproof','water resistant'],atmos:['atmos','dolby atmos','surround'],streaming:['streaming','netflix','youtube'], 'high-refresh':['high refresh','144hz','165hz','240hz'],
  dynamic:['dynamic','podcast','voice'],xlr:['xlr','audio interface'],rugged:['rugged','durable'],laptop:['laptop','macbook'],stylus:['stylus','pen','drawing'],colour:['colour','color','colour screen'], 'pressure-sensor':['pressure sensor','gum protection'],
  'heat-control':['heat control','heat protection'],bread:['bread','dough'], 'large-batch':['large batch','big batch'],ice:['ice','frozen'], 'fuzzy-logic':['fuzzy logic','rice programs'],pressure:['pressure cook','pressure cooker'], 'reverse-osmosis':['reverse osmosis','ro water'],wifi:['wifi','wi fi','wi-fi']
};
const NEGATIVE_PREFIXES=['no ','not ','without ','avoid ','avoiding ','exclude ','excluding ','dont want ','do not want ','dont need ','do not need '];
function extractBudget(input){const n=norm(input).replace(/,/g,'');const explicit=n.match(/(?:under|below|less than|up to|max(?:imum)?|budget(?: of)?|around)\s*\$?\s*(\d{2,5})/);if(explicit)return Number(explicit[1]);const dollar=n.match(/\$(\d{2,5})/);return dollar?Number(dollar[1]):null;}
function detectCategory(input,forced=''){if(forced&&categories[forced])return categories[forced];const n=norm(input);let best=null;for(const [slug,list] of Object.entries(CATEGORY_ALIASES)){let score=0;for(const alias of list){const a=norm(alias);if(a&&n.includes(a))score=Math.max(score,a.length);}if(score&&(!best||score>best.score))best={slug,score};}return best?categories[best.slug]:null;}
function detectBrand(input,forced=''){if(forced){const f=norm(forced);const hit=[...new Set(products.map(p=>p.brand))].find(b=>norm(b)===f||slugify(b)===forced);if(hit)return hit;}const n=norm(input);return [...new Set(products.map(p=>p.brand))].sort((a,b)=>b.length-a.length).find(b=>n.includes(norm(b)))||null;}
function phraseIsNegative(n,alias){const a=norm(alias);return NEGATIVE_PREFIXES.some(prefix=>n.includes(norm(prefix+a)));}
function detectTags(input){const n=norm(input),positive=new Set(),excluded=new Set();for(const [tag,list] of Object.entries(TAG_ALIASES))for(const alias of list){const a=norm(alias);if(!a||!n.includes(a))continue;if(phraseIsNegative(n,alias))excluded.add(tag);else positive.add(tag);}for(const x of excluded)positive.delete(x);return {positive:[...positive],excluded:[...excluded]};}
function structuredIntent(input,category){const n=norm(input),out={};if(category?.slug==='coffee-machines'){if(/\b(one touch|one-touch|automatic|bean to cup|bean-to-cup|hands off|hands-off)\b/.test(n))out.workflow='one-touch';else if(/\b(guided|assisted|touchscreen)\b/.test(n))out.workflow='guided';else if(/\b(manual|portafilter|hands on|hands-on)\b/.test(n))out.workflow='manual';if(/\b(very easy|easy|simple|low effort|low-effort|almost no learning)\b/.test(n))out.learning='low';if(/\b(switch beans|bean switch|different beans|decaf|two beans)\b/.test(n))out.beanSwitch=true;if(/\b(cold brew|cold coffee|iced coffee|iced)\b/.test(n))out.cold=true;if(/\b(compact|small kitchen|small space|apartment|narrow)\b/.test(n))out.compact=true;}return out;}
function interpretQuery(query='',opts={}){const category=detectCategory(query,opts.category||''),brand=detectBrand(query,opts.brand||''),detected=detectTags(query),positive=new Set(detected.positive),excluded=new Set(detected.excluded);if(category?.slug==='wireless-headphones'&&positive.has('quiet')){positive.delete('quiet');positive.add('anc');}if(opts.priority)positive.add(opts.priority);if(opts.secondary&&opts.secondary!==opts.priority)positive.add(opts.secondary);if(opts.position==='value')positive.add('value');if(opts.position==='premium')positive.add('premium');if(opts.avoid)excluded.add(opts.avoid);for(const x of excluded)positive.delete(x);const budget=Number(opts.budget)||extractBudget(query)||null,structured=structuredIntent(query,category),signals=[...positive,...excluded];if(brand)signals.push('brand');if(budget)signals.push('budget');signals.push(...Object.keys(structured));return {query:String(query||'').trim(),category,categorySlug:category?.slug||null,brand,budget,positiveTags:[...positive],excludedTags:[...excluded],structured,signalCount:new Set(signals).size};}
function directTextScore(query,p){const tokens=words(query).filter(t=>t.length>1&&!STOP.has(t));if(!tokens.length)return 0;const hay=norm([p.brand,p.name,p.summary,p.categoryLabel,(p.tags||[]).join(' '),(p.highlights||[]).join(' ')].join(' '));let score=0;for(const t of tokens)if(hay.includes(t))score+=1.5;if(norm(query).includes(norm(p.name)))score+=12;if(norm(query).includes(norm(p.brand)))score+=4;return Math.min(score,18);}
function scoreProduct(p,intent){let score=0;const reasons=[],gaps=[],conflicts=[];let matched=0,requested=0;if(intent.categorySlug){if(p.category===intent.categorySlug){score+=38;reasons.push(`In the ${p.categoryLabel} maintained set`);}else score-=120;}for(const tag of intent.positiveTags){requested++;if((p.tags||[]).includes(tag)){score+=24;matched++;reasons.push(`Matches ${human(tag)}`);}else gaps.push(`Does not carry the maintained ${human(tag)} signal`);}for(const tag of intent.excludedTags){requested++;if((p.tags||[]).includes(tag)){score-=62;conflicts.push(`Conflicts with your avoid-${human(tag)} preference`);}else{score+=5;matched++;}}if(intent.brand){requested++;if(norm(p.brand)===norm(intent.brand)){score+=22;matched++;reasons.push(`Matches your ${p.brand} brand preference`);}else score-=5;}if(intent.budget){requested++;if(p.price){if(p.price<=intent.budget){score+=20;matched++;reasons.push(`Maintained price basis is within your A$${intent.budget.toLocaleString('en-AU')} ceiling`);}else{score-=35;conflicts.push(`Maintained price basis is above your A$${intent.budget.toLocaleString('en-AU')} ceiling`);}}else gaps.push('Current price is not maintained, so budget fit needs retailer verification');}
if(intent.categorySlug==='coffee-machines'){const s=intent.structured;if(s.workflow){requested++;if(p.workflow===s.workflow){score+=28;matched++;reasons.push(`Matches your ${human(s.workflow)} workflow preference`);}else if(s.workflow==='one-touch'&&p.workflow==='guided'){score+=4;gaps.push('Guided rather than fully one-touch');}else score-=10;}if(s.learning==='low'){requested++;if(p.learning==='low'){score+=22;matched++;reasons.push('Low-learning workflow in the maintained data');}else if(p.learning==='medium'){score+=5;gaps.push('Some technique or setup remains');}else{score-=12;gaps.push('Higher learning burden');}}if(s.beanSwitch){requested++;if(p.beanSwitch){score+=30;matched++;reasons.push('Dedicated bean-switching support');}else{score-=9;gaps.push('No dedicated bean-switching system in maintained data');}}if(s.cold){requested++;if(p.cold){score+=30;matched++;reasons.push('Documented cold-coffee capability');}else{score-=14;gaps.push('Cold extraction is not documented in maintained data');}}if(s.compact){requested++;if(p.width<=280){score+=24;matched++;reasons.push(`Compact ${p.width} mm maintained width`);}else if(p.width<=340){score+=8;gaps.push(`Moderate ${p.width} mm maintained width`);}else{score-=8;gaps.push(`Wider ${p.width} mm maintained width`);}}}
score+=directTextScore(intent.query,p);if(p.evidenceTier==='deep')score+=2;return {p,score,reasons:[...new Set(reasons)],gaps:[...new Set(gaps)],conflicts:[...new Set(conflicts)],matched,requested};}
function labelFor(result,signalCount,margin){if(!signalCount)return 'Exploratory match';const ratio=result.requested?result.matched/result.requested:0;if(!result.conflicts.length&&signalCount>=2&&ratio>=0.7&&margin>=8)return 'Strong match';if(!result.conflicts.length&&ratio>=0.5)return 'Good match';if(result.conflicts.length)return 'Compromise match';return 'Exploratory match';}
function rankDecision(query='',opts={}){const intent=interpretQuery(query,opts);let pool=intent.categorySlug?products.filter(p=>p.category===intent.categorySlug):products;if(!pool.length)pool=products;const ranked=pool.map(p=>scoreProduct(p,intent)).sort((a,b)=>b.score-a.score||b.matched-a.matched||a.p.name.localeCompare(b.p.name));ranked.forEach((r,i)=>{const next=ranked[i+1],margin=i===0?(next?r.score-next.score:r.score):0;r.matchLabel=labelFor(r,intent.signalCount,margin);r.coverage=r.requested?`${r.matched}/${r.requested} stated needs matched`:'Explore this fit';});return {intent,ranked};}
function describeIntent(intent){const bits=[];if(intent.category)bits.push(intent.category.label);if(intent.positiveTags.length)bits.push(...intent.positiveTags.map(human));if(intent.excludedTags.length)bits.push(...intent.excludedTags.map(x=>`Avoid ${human(x)}`));if(intent.brand)bits.push(intent.brand);if(intent.budget)bits.push(`Up to A$${intent.budget.toLocaleString('en-AU')}`);if(intent.structured.workflow)bits.push(`${human(intent.structured.workflow)} workflow`);if(intent.structured.beanSwitch)bits.push('Bean switching');return [...new Set(bits)];}
function publicDecision(query='',opts={}){const {intent,ranked}=rankDecision(query,opts);return {version:'decision-engine-v3',basis:'Maintained APG data, category-specific decision signals and explicit shopper preferences',commercialRecommendationWeight:0,interpretation:{category:intent.category?.label||null,brand:intent.brand,budget:intent.budget,priorities:intent.positiveTags,avoid:intent.excludedTags,signals:describeIntent(intent),decisionFactors:intent.category?.factors||[]},results:ranked.slice(0,5).map(r=>({slug:r.p.slug,brand:r.p.brand,name:r.p.name,category:r.p.categoryLabel,evidenceTier:r.p.evidenceTier||'deep',freshnessStatus:r.p.freshnessStatus||null,match:r.matchLabel,coverage:r.coverage,reasons:r.reasons.slice(0,4),gaps:r.gaps.slice(0,3),conflicts:r.conflicts,tradeoff:r.p.watch,priceBasis:r.p.price||null,url:`/products/${r.p.slug}/`})),note:'Match labels describe fit to stated preferences, not product performance ratings or hands-on test scores. Starter-evidence products need deeper specification verification before APG makes stronger category claims.'};}
module.exports={rankDecision,interpretQuery,describeIntent,publicDecision,human,norm};