const decisionCss=`
/* APG Decision Intelligence v2 */
.decision-hero{padding:64px 0 44px;background:linear-gradient(135deg,#071d2e 0%,#0b3446 55%,#08786f 100%);color:#fff;position:relative;overflow:hidden}
.decision-hero:after{content:"";position:absolute;width:420px;height:420px;border:1px solid rgba(255,255,255,.12);border-radius:50%;right:-110px;top:-170px;box-shadow:0 0 0 80px rgba(255,255,255,.025),0 0 0 160px rgba(255,255,255,.018);pointer-events:none}
.decision-hero .kicker{color:#9fe0d8}.decision-hero h1{max-width:820px;color:#fff}.decision-hero .lede{max-width:780px;color:#e2f1ef}
.decision-hero-grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(280px,.7fr);gap:36px;align-items:end;position:relative;z-index:1}
.decision-principles{display:flex;flex-wrap:wrap;gap:8px;margin-top:24px}.decision-principles span{border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.08);padding:8px 11px;border-radius:999px;font-size:.82rem;color:#eef8f6}
.decision-engine-card{background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.2);backdrop-filter:blur(10px);padding:24px;border-radius:22px;box-shadow:0 20px 50px rgba(0,0,0,.12)}
.decision-engine-card .engine-status{display:inline-flex;font-size:.72rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;background:#e8ad54;color:#102f4a;padding:6px 9px;border-radius:999px;margin-bottom:12px}.decision-engine-card strong{display:block;font-size:1.25rem;margin-bottom:8px}.decision-engine-card p{color:#deeeec;margin:0 0 14px}.decision-engine-card a{color:#fff;font-weight:700}
.decision-shell{display:grid;grid-template-columns:minmax(0,1.8fr) minmax(260px,.65fr);gap:28px;align-items:start}.decision-form{border:1px solid #dbe7e5;background:#fff;border-radius:24px;padding:28px;box-shadow:0 12px 36px rgba(12,47,66,.06)}
.decision-query label,.decision-fields label{display:block;font-weight:800;color:#102f4a;margin-bottom:7px}.decision-query textarea,.decision-fields input,.decision-fields select{width:100%;border:1px solid #bfd1cf;border-radius:13px;padding:13px 14px;background:#fff;color:#152b38;font:inherit}.decision-query textarea{resize:vertical;min-height:108px;line-height:1.5}.decision-query textarea:focus,.decision-fields input:focus,.decision-fields select:focus{outline:3px solid rgba(8,120,111,.16);border-color:#08786f}.decision-query small{display:block;color:#5f747d;margin-top:7px}
.decision-fields{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;margin-top:20px}.decision-form-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:20px}.decision-form-actions span{font-size:.82rem;color:#687b83;max-width:480px}
.decision-examples{border:1px solid #dbe7e5;border-radius:24px;background:#f7faf9;padding:22px;display:grid;gap:10px}.decision-examples a{display:grid;grid-template-columns:1fr auto;gap:10px;text-decoration:none;color:#183b4b;background:#fff;border:1px solid #dfeae8;border-radius:13px;padding:13px;font-weight:650}.decision-examples a:hover{border-color:#8bbdb7;transform:translateY(-1px)}
.decision-summary{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.2fr) auto;gap:24px;align-items:center}.decision-signals{display:flex;flex-wrap:wrap;gap:7px}.decision-share{display:grid;gap:7px;justify-items:end}.decision-share span{font-size:.78rem;color:#567078}
.decision-results{display:grid;gap:22px}.decision-result{border:1px solid #dbe6e4;border-radius:24px;background:#fff;overflow:hidden;box-shadow:0 8px 30px rgba(18,56,70,.055)}.decision-result-top{border-color:#8fc9c1;box-shadow:0 16px 44px rgba(8,120,111,.09)}
.decision-rank{display:flex;justify-content:space-between;gap:15px;align-items:center;padding:13px 20px;border-bottom:1px solid #e5eeec;background:#f7faf9}.decision-rank>span{font-size:.82rem;text-transform:uppercase;letter-spacing:.06em;font-weight:800;color:#577078}.decision-match{padding:6px 10px;border-radius:999px;font-size:.78rem}.decision-match.strong{background:#d9f2ec;color:#075a52}.decision-match.good{background:#e9f4f1;color:#225d58}.decision-match.compromise{background:#fff1dc;color:#7c5414}.decision-match.explore{background:#edf1f3;color:#4f626a}
.decision-result-grid{display:grid;grid-template-columns:minmax(230px,.65fr) minmax(0,1.35fr);gap:26px;padding:24px;align-items:start}.decision-result-copy h2{margin-top:3px}.decision-coverage{display:inline-flex;margin:6px 0 14px;padding:6px 10px;border-radius:8px;background:#f0f6f4;color:#315f5a;font-size:.82rem;font-weight:700}
.decision-reasons,.decision-caution{border-radius:14px;padding:14px 16px;margin:12px 0}.decision-reasons{background:#f3f9f7;border:1px solid #d8ebe7}.decision-caution{background:#fff8ec;border:1px solid #f2d7a5}.decision-reasons strong,.decision-caution strong{display:block;margin-bottom:6px}.decision-reasons ul,.decision-caution ul,.decision-gaps ul{margin:0;padding-left:19px}.decision-reasons li,.decision-caution li,.decision-gaps li{margin:4px 0}
.decision-gaps{border-top:1px solid #e3ecea;border-bottom:1px solid #e3ecea;padding:11px 0;margin:13px 0}.decision-gaps summary{cursor:pointer;font-weight:700;color:#3e5b65}.decision-tradeoff{display:grid;grid-template-columns:auto 1fr;gap:12px;padding:12px 0}.decision-tradeoff strong{color:#102f4a}.decision-tradeoff span{color:#536a73}.decision-price{margin:8px 0 14px}
.decision-disclaimer{margin-top:24px;border-left:4px solid #08786f;background:#f4f8f7;padding:17px 20px;border-radius:0 13px 13px 0}.decision-disclaimer p{margin-bottom:0}.decision-onboarding>div:first-child{margin-bottom:22px}
.workspace-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.workspace-panel{border:1px solid #dbe7e5;border-radius:22px;padding:22px;background:#fff;min-height:220px}.workspace-list{display:grid;gap:9px}.workspace-item{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:12px 13px;border:1px solid #e1eae9;border-radius:12px;text-decoration:none;color:#173b4b;background:#fbfcfc}.workspace-item strong{display:block}.workspace-item small{color:#677a82}.workspace-empty{border:1px dashed #c7d8d5;border-radius:13px;padding:18px;color:#667b83;background:#f8faf9}.workspace-controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:24px}.workspace-controls span{color:#5f747d;font-size:.82rem}
.apg-power-link{font-weight:800!important;color:#08786f!important}.apg-workspace-link{position:relative}.apg-workspace-badge{display:inline-flex;min-width:18px;height:18px;padding:0 5px;border-radius:999px;align-items:center;justify-content:center;background:#e8ad54;color:#102f4a;font-size:10px;font-weight:900;margin-left:4px}
@media(max-width:900px){.decision-hero-grid,.decision-shell,.decision-summary,.decision-result-grid{grid-template-columns:1fr}.decision-fields{grid-template-columns:1fr 1fr}.decision-share{justify-items:start}.workspace-grid{grid-template-columns:1fr}.decision-result-grid>.product-visual,.decision-result-grid>.product-photo{max-width:520px}.decision-hero{padding-top:44px}}
@media(max-width:620px){.decision-fields{grid-template-columns:1fr}.decision-form{padding:20px}.decision-result-grid{padding:17px}.decision-rank{align-items:flex-start;flex-direction:column}.decision-tradeoff{grid-template-columns:1fr}.decision-hero{padding:36px 0}.decision-principles{gap:6px}.decision-principles span{font-size:.75rem}.workspace-panel{padding:17px}}
`;
module.exports={decisionCss};
