const platformV7Css=`
/* Australian Product Guide — Premium Visual Identity v7
   Calm, high-information shopping UI with an original guided-choice brand language. */
:root{
 --v7-ink:#092b3d;--v7-ink-2:#123f50;--v7-teal:#08786f;--v7-teal-2:#0c9184;
 --v7-mint:#e7f5f1;--v7-mint-2:#d8eee8;--v7-cream:#fbf7ed;--v7-sand:#f3ead8;
 --v7-signal:#f4b45f;--v7-coral:#e97e62;--v7-sky:#dfeef5;--v7-paper:#fff;
 --v7-text:#142d37;--v7-muted:#60747b;--v7-line:#d9e4e2;--v7-line-strong:#bdd2ce;
 --v7-shadow:0 18px 50px rgba(11,48,68,.10);--v7-shadow-soft:0 8px 26px rgba(11,48,68,.075);
 --v7-radius:22px;--v7-radius-sm:14px;
}
body[data-platform-v7=true]{background:#fbfcfb;color:var(--v7-text);font-feature-settings:"kern" 1,"liga" 1;text-rendering:optimizeLegibility}
body[data-platform-v7=true] .wrap{max-width:1240px}
body[data-platform-v7=true] h1,body[data-platform-v7=true] h2,body[data-platform-v7=true] h3{color:var(--v7-ink);letter-spacing:-.025em}
body[data-platform-v7=true] h1{letter-spacing:-.045em}
body[data-platform-v7=true] a:focus-visible,body[data-platform-v7=true] button:focus-visible,body[data-platform-v7=true] input:focus-visible,body[data-platform-v7=true] summary:focus-visible{outline:3px solid rgba(244,180,95,.8);outline-offset:3px;border-radius:7px}

/* Brand */
.v7-logo-lockup{display:inline-flex;align-items:center;gap:11px;color:var(--v7-ink);min-width:0}
.v7-logo-mark{width:47px;height:47px;display:grid;place-items:center;flex:0 0 auto;filter:drop-shadow(0 5px 12px rgba(11,48,68,.12))}
.v7-logo-mark svg{display:block;width:100%;height:100%}
.v7-logo-type{display:flex;flex-direction:column;line-height:1.05;min-width:0}
.v7-logo-type strong{font-size:17px;letter-spacing:-.025em;color:currentColor;white-space:nowrap}
.v7-logo-type small{font-size:10.5px;color:#63777d;margin-top:5px;letter-spacing:.005em;white-space:nowrap}
.v7-logo-lockup.is-dark{color:#f7fbfa}.v7-logo-lockup.is-dark .v7-logo-type strong{color:#fff}.v7-logo-lockup.is-dark .v7-logo-type small{color:#bcd9d5}
.v7-logo-lockup.is-compact .v7-logo-mark{width:58px;height:58px}
.site-header .brand{min-width:248px;text-decoration:none}
.utility{background:var(--v7-ink)!important;border:0!important}.utility-inner{min-height:32px;color:#c8dfdc!important}.utility a{color:#e8f3f1!important}
.masthead{min-height:82px;gap:24px}.site-header{box-shadow:0 1px 0 rgba(12,57,70,.08);backdrop-filter:saturate(1.08)}

/* Header, search and navigation */
.header-search{flex:1;max-width:650px}.global-search{border:1px solid var(--v7-line-strong)!important;border-radius:16px!important;background:#fff!important;box-shadow:0 5px 18px rgba(11,48,68,.06)!important;min-height:50px}
.global-search:focus-within{border-color:var(--v7-teal)!important;box-shadow:0 0 0 4px rgba(8,120,111,.11),0 8px 24px rgba(11,48,68,.08)!important}
.global-search input{font-size:15px!important}.global-search button{border-radius:11px!important;margin:5px!important;background:var(--v7-ink)!important;padding-inline:20px!important}
.search-suggestions{border:1px solid var(--v7-line)!important;border-radius:18px!important;box-shadow:0 24px 70px rgba(7,38,53,.18)!important;overflow:hidden!important;margin-top:9px!important;background:#fff!important;z-index:999!important}
.search-suggestions [role=option],.search-suggestions a{min-height:58px!important;border-bottom:1px solid #edf2f1!important;padding:11px 14px!important}
.search-suggestions [aria-selected=true],.search-suggestions a:hover{background:var(--v7-mint)!important}
.header-action{border-radius:13px!important}.header-action:hover{background:var(--v7-mint)!important;color:var(--v7-teal)!important}
.primary-nav{border-top:1px solid #eef3f2!important;border-bottom:1px solid #e2eae8!important;background:rgba(255,255,255,.97)!important}
.nav-inner>a,.nav-trigger{font-weight:680!important;font-size:13.5px!important;padding:13px 15px!important;border-radius:10px!important}
.nav-inner>a:hover,.nav-trigger:hover,.nav-inner>a[aria-current=page]{background:var(--v7-mint)!important;color:var(--v7-teal)!important}
.apg-power-link{color:var(--v7-teal)!important}
.mega-surface.platform-mega{border:1px solid var(--v7-line)!important;border-radius:0 0 26px 26px!important;box-shadow:0 28px 72px rgba(7,38,53,.18)!important;padding:26px!important}
.mega-grid{gap:16px!important}.mega-group{padding:9px 11px!important;border-radius:15px}.mega-group:hover{background:#fafcfb}.mega-title{color:var(--v7-muted)!important;font-size:11px!important;letter-spacing:.11em!important;text-transform:uppercase!important}
.mega-group a{border-radius:10px!important;padding:9px 10px!important}.mega-group a:hover{background:var(--v7-mint)!important;color:var(--v7-teal)!important}.mega-group a small{color:#72868c!important}
.mega-feature{background:linear-gradient(145deg,var(--v7-ink),#0e6264)!important;border-radius:20px!important;color:#eaf5f3!important;padding:22px!important;position:relative;overflow:hidden}.mega-feature:before{content:"";position:absolute;width:180px;height:180px;border-radius:50%;background:radial-gradient(circle,rgba(244,180,95,.25),transparent 68%);right:-55px;top:-80px}.mega-feature h3{color:#fff!important}.mega-feature .button{background:#fff!important;color:var(--v7-ink)!important}

/* Hero architecture */
.hero-shell{background:linear-gradient(180deg,#f5faf8 0,#fbfcfb 100%)!important;border-bottom:1px solid #e6efed}.hero{position:relative;overflow:hidden;border:1px solid var(--v7-line);border-radius:26px;padding:42px 44px!important;margin:25px 0;background:linear-gradient(135deg,#fff 0,#f5faf8 64%,#eef7f4 100%);box-shadow:var(--v7-shadow-soft)}
.hero:after{content:"";position:absolute;width:360px;height:360px;right:-150px;top:-190px;border-radius:50%;background:radial-gradient(circle,rgba(8,120,111,.14),rgba(8,120,111,0) 68%);pointer-events:none}.hero .lede{max-width:760px!important}
.kicker{color:var(--v7-teal)!important;font-weight:780!important;letter-spacing:.09em!important;text-transform:uppercase!important;font-size:11px!important}
.button{border-radius:12px!important;font-weight:720!important;box-shadow:none!important}.button:not(.secondary){background:var(--v7-ink)!important}.button:not(.secondary):hover{background:#125a61!important;transform:translateY(-1px)}.button.secondary{border:1px solid var(--v7-line-strong)!important;background:#fff!important;color:var(--v7-ink)!important}.button.secondary:hover{border-color:var(--v7-teal)!important;background:var(--v7-mint)!important;color:var(--v7-teal)!important}

/* Category illustration language */
.v7-category-scene{--scene:#08786f;--scene2:#dff3ed;position:relative;isolation:isolate;overflow:hidden;min-height:172px;border-radius:20px;background:linear-gradient(145deg,#eef8f5 0,#dcefeb 58%,#f8f2e7 100%);display:flex;align-items:flex-end;padding:20px;color:var(--v7-ink)}
.v7-category-scene:before,.v7-category-scene:after{content:"";position:absolute;pointer-events:none;z-index:-1}.v7-category-scene:before{width:160px;height:160px;right:-30px;top:-40px;border-radius:50%;background:radial-gradient(circle,rgba(244,180,95,.28),rgba(244,180,95,0) 70%)}.v7-category-scene:after{width:120px;height:80px;left:-20px;bottom:-32px;border-radius:50%;background:rgba(255,255,255,.6);transform:rotate(-12deg)}
.v7-scene-icon{position:absolute;right:16px;top:14px;width:96px;height:96px;display:grid;place-items:center;color:var(--scene);filter:drop-shadow(0 8px 14px rgba(11,48,68,.08))}.v7-scene-icon svg{width:100%;height:100%;stroke-width:2.35}.v7-scene-copy{display:flex;flex-direction:column;position:relative;z-index:2}.v7-scene-copy small{font-size:10px;text-transform:uppercase;letter-spacing:.11em;font-weight:780;color:#61767b}.v7-scene-copy strong{font-size:16px;letter-spacing:-.02em;margin-top:3px;max-width:160px}
.v7-category-scene.compact{min-height:0;width:98px;height:98px;padding:0;border-radius:22px;align-items:initial;background:linear-gradient(145deg,#e7f5f1,#f9f2e5)}.v7-category-scene.compact .v7-scene-icon{width:70px;height:70px;right:14px;top:12px}.v7-category-scene.compact .v7-scene-copy,.v7-category-scene.compact .v7-scene-glow{display:none}
/* Visual families — cohesive colour shifts, distinct category glyphs provide recognition. */
[data-v7-category="coffee-machines"],[data-v7-category="air-fryers"],[data-v7-category="kitchen-mixers"],[data-v7-category="blenders"],[data-v7-category="rice-cookers"],[data-v7-category="multicookers"],[data-v7-category="vacuum-sealers"],[data-v7-category="water-filters"]{--scene:#9c5f2f;--scene2:#f4e3cc}
[data-v7-category="wireless-headphones"],[data-v7-category="earbuds"],[data-v7-category="bluetooth-speakers"],[data-v7-category="soundbars"],[data-v7-category="gaming-headsets"],[data-v7-category="microphones"]{--scene:#6954a3;--scene2:#ece7fa}
[data-v7-category="computer-monitors"],[data-v7-category="gaming-monitors"],[data-v7-category="portable-monitors"],[data-v7-category="tablets"],[data-v7-category="external-ssds"],[data-v7-category="mechanical-keyboards"],[data-v7-category="computer-mice"],[data-v7-category="webcams"]{--scene:#276d97;--scene2:#dceef8}
[data-v7-category="home-security-cameras"],[data-v7-category="smart-doorbells"],[data-v7-category="mesh-wifi-systems"],[data-v7-category="baby-monitors"],[data-v7-category="automatic-pet-feeders"]{--scene:#08786f;--scene2:#dff3ed}
[data-v7-category="robot-vacuums"],[data-v7-category="stick-vacuums"],[data-v7-category="air-purifiers"],[data-v7-category="dehumidifiers"],[data-v7-category="portable-air-conditioners"]{--scene:#39798a;--scene2:#e1f1f3}
[data-v7-category="smartwatches"],[data-v7-category="fitness-trackers"],[data-v7-category="home-fitness-equipment"],[data-v7-category="electric-toothbrushes"],[data-v7-category="hair-dryers"],[data-v7-category="electric-shavers"]{--scene:#b85e6b;--scene2:#f7e5e8}
[data-v7-category="luggage"],[data-v7-category="dash-cameras"],[data-v7-category="power-banks"],[data-v7-category="portable-power-stations"],[data-v7-category="e-readers"]{--scene:#b16f30;--scene2:#f6ead8}
[data-v7-category="cordless-drills"],[data-v7-category="pressure-washers"],[data-v7-category="standing-desks"],[data-v7-category="office-chairs"],[data-v7-category="projectors"]{--scene:#536c75;--scene2:#e8eef0}
.v7-category-scene{background:linear-gradient(145deg,var(--scene2,#e7f5f1) 0,#fff 100%)}
.v7-category-scene .v7-scene-icon{color:var(--scene,#08786f)}

/* Category index cards */
.premium-category-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:20px!important}.v7-category-card{display:grid!important;grid-template-rows:172px 1fr!important;padding:8px!important;background:#fff!important;border:1px solid var(--v7-line)!important;border-radius:24px!important;box-shadow:0 5px 18px rgba(11,48,68,.045)!important;overflow:hidden;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.v7-category-card:hover{transform:translateY(-3px);box-shadow:var(--v7-shadow-soft)!important;border-color:#b8d1cd!important}.v7-category-card-copy{padding:18px 16px 15px!important;display:flex;flex-direction:column}.v7-category-card-copy h3{font-size:21px!important}.v7-category-card-copy p:not(.eyebrow){color:#52686f!important;line-height:1.6}.v7-category-card-copy .card-actions{margin-top:auto!important;padding-top:15px!important}

/* Product cards and visual system */
.product-grid{gap:20px!important}.product-card.v7-product-card{border:1px solid var(--v7-line)!important;border-radius:24px!important;background:#fff!important;overflow:hidden;box-shadow:0 5px 20px rgba(11,48,68,.055)!important;transition:transform .18s ease,box-shadow .18s ease}.product-card.v7-product-card:hover{transform:translateY(-3px);box-shadow:var(--v7-shadow)!important}.v7-product-card .product-visual{border:0!important;border-radius:0!important;background:linear-gradient(145deg,var(--scene2,#e8f5f2),#fff)!important;min-height:220px!important}.v7-product-card .product-art{min-height:142px!important;background:transparent!important;display:grid!important;place-items:center!important;position:relative!important}.v7-product-card .product-art>.category-icon{display:none!important}.v7-product-card .product-art>.v7-category-scene.compact{width:132px;height:132px;border-radius:30px;box-shadow:0 15px 35px rgba(11,48,68,.10);transform:rotate(-2deg)}.v7-product-card .product-art>.v7-category-scene.compact .v7-scene-icon{width:92px;height:92px;right:20px;top:18px}.v7-product-card .art-halo{width:180px!important;height:180px!important;background:radial-gradient(circle,rgba(255,255,255,.92),rgba(255,255,255,0) 68%)!important}.v7-product-card .art-model{bottom:10px!important;background:rgba(255,255,255,.88)!important;border:1px solid rgba(11,48,68,.08)!important;color:var(--v7-ink)!important;padding:5px 9px!important;border-radius:999px!important;font-size:10px!important;font-weight:760!important}.v7-product-card .visual-copy{background:#fff!important;border-top:1px solid #edf2f1!important;padding:13px 16px!important}.v7-product-card .visual-copy small{font-size:9.5px!important;color:#788b90!important}.product-card-body{padding:18px!important}.card-meta{gap:10px!important}.freshness{font-size:10.5px!important;color:#60777d!important}.best-for{border-radius:12px!important;background:#f4faf8!important;border:1px solid #e0eeeb!important;padding:10px 12px!important}.best-for span{font-size:9px!important;text-transform:uppercase!important;letter-spacing:.09em!important;color:#6c8085!important}.best-for strong{color:var(--v7-ink)!important}.pills{gap:6px!important}.pill{border-radius:999px!important;border:1px solid #dce7e5!important;background:#f8faf9!important;color:#496169!important}.card-actions{gap:7px!important}.compare-button,.save-button{border-radius:11px!important}.save-button{font-size:18px!important}

/* Product page */
.product-hero,.product-detail-hero{border-radius:26px!important;border:1px solid var(--v7-line)!important;box-shadow:var(--v7-shadow-soft)!important;background:linear-gradient(140deg,#fff 0,#f4faf8 100%)!important}.product-visual.large{border-radius:24px!important;background:linear-gradient(145deg,#e6f4f0,#fff)!important}.product-hero .price,.product-detail-hero .price{font-size:28px!important;color:var(--v7-ink)!important}.retailer-panel,.evidence-box{border-radius:22px!important;border-color:var(--v7-line)!important;box-shadow:0 5px 18px rgba(11,48,68,.045)!important}.retailer-row{border-radius:14px!important}.retailer-row:hover{background:var(--v7-mint)!important}.independence-badge{background:var(--v7-mint)!important;color:var(--v7-teal)!important;border-radius:999px!important}.evidence-grid>div{background:#f8faf9!important;border-radius:13px!important;padding:13px!important}.section{padding-top:52px!important;padding-bottom:52px!important}.section-head{margin-bottom:22px!important}.soft-panel{border-radius:26px!important;background:linear-gradient(145deg,#f6faf8,#fbf8f0)!important;border:1px solid #e5ece9!important;padding:30px!important}

/* Comparison + Difference Engine */
.compare-hero,.comparison-shell,.difference-engine{border-radius:26px!important}.difference-engine{background:linear-gradient(145deg,#0a3043,#0b6668)!important;color:#e9f5f3!important;border:0!important;box-shadow:var(--v7-shadow)!important;position:relative;overflow:hidden}.difference-engine:after{content:"";position:absolute;width:330px;height:330px;border-radius:50%;right:-145px;top:-170px;background:radial-gradient(circle,rgba(244,180,95,.28),transparent 66%)}.difference-engine h2,.difference-engine h3{color:#fff!important}.difference-engine .kicker{color:#9ee0d6!important}.difference-engine article,.difference-card{background:rgba(255,255,255,.08)!important;border:1px solid rgba(255,255,255,.15)!important;border-radius:17px!important;backdrop-filter:blur(8px)}.comparison-table{border-radius:18px!important;overflow:hidden!important;border:1px solid var(--v7-line)!important}.comparison-table th{background:#edf7f4!important;color:var(--v7-ink)!important}.comparison-table tr:nth-child(even) td{background:#fbfcfb!important}

/* Decision Lab signature */
body[data-platform-page="/decision-lab/"] .hero{padding-right:min(42%,440px)!important;min-height:310px}.v7-signature-illustration{position:absolute;right:30px;top:26px;width:34%;min-width:280px;height:250px;border-radius:24px;background:linear-gradient(145deg,#0c4654,#08786f);overflow:hidden;box-shadow:0 18px 45px rgba(11,48,68,.18)}.v7-decision-art span{position:absolute;width:110px;height:3px;background:rgba(255,255,255,.75);left:34px;transform-origin:left center}.v7-decision-art span:nth-child(1){top:65px;transform:rotate(18deg)}.v7-decision-art span:nth-child(2){top:125px;width:155px}.v7-decision-art span:nth-child(3){top:184px;transform:rotate(-18deg)}.v7-decision-art b{position:absolute;right:54px;top:95px;width:54px;height:54px;border-radius:18px;background:var(--v7-signal);box-shadow:0 0 0 14px rgba(255,255,255,.1)}.decision-lab,.decision-form,.decision-results{border-radius:22px!important}.decision-form{background:#fff!important;border:1px solid var(--v7-line)!important;box-shadow:var(--v7-shadow-soft)!important}.decision-form input,.decision-form select,.decision-form textarea{border-radius:12px!important;border-color:var(--v7-line-strong)!important;min-height:48px}.match-card,.reason-card{border-radius:18px!important;border-color:var(--v7-line)!important}.match-indicator{background:linear-gradient(90deg,var(--v7-teal),#5fb5a8)!important}

/* My APG signature */
body[data-platform-page="/my-apg/"] .hero{padding-right:min(42%,440px)!important;min-height:300px}.v7-workspace-art{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:28px;background:linear-gradient(145deg,#e5f4f0,#fff)}.v7-workspace-art span{display:block;border-radius:16px;background:#fff;border:1px solid var(--v7-line);box-shadow:0 8px 18px rgba(11,48,68,.08)}.v7-workspace-art span:nth-child(1){grid-row:span 2;background:linear-gradient(160deg,#0d5360,#08786f)}.v7-workspace-art span:nth-child(3){background:linear-gradient(145deg,#fff2dc,#fff)}.workspace-grid,.my-apg-grid{gap:18px!important}.workspace-card,.my-apg-card{border-radius:20px!important;border-color:var(--v7-line)!important;box-shadow:0 5px 18px rgba(11,48,68,.04)!important}

/* Brand, guide and editorial pages */
.brand-card,.guide-card,.platform-card,.trust-card{border-radius:20px!important;border-color:var(--v7-line)!important;box-shadow:0 5px 18px rgba(11,48,68,.045)!important}.brand-card:hover,.guide-card:hover{box-shadow:var(--v7-shadow-soft)!important;transform:translateY(-2px)}
.v7-editorial-main .hero{background:linear-gradient(135deg,#fff,#edf7f4)!important}.v7-editorial-main .policy-layout,.v7-editorial-main .trust-layout,.v7-editorial-main .article-layout{gap:34px!important}.v7-editorial-main article,.v7-editorial-main .policy-content{line-height:1.75!important}.v7-editorial-main article h2,.v7-editorial-main .policy-content h2{padding-top:18px!important;border-top:1px solid #e3ecea!important;margin-top:36px!important}.v7-editorial-main .policy-nav,.v7-editorial-main .toc{border-radius:18px!important;border:1px solid var(--v7-line)!important;background:#fff!important;box-shadow:0 8px 24px rgba(11,48,68,.045)!important}

/* Page-level category scene */
.v7-page-scene{float:right;width:300px;margin:-10px 0 12px 34px}.v7-page-scene .v7-category-scene{min-height:190px}.v7-page-scene+.kicker{}

/* Footer */
footer{background:linear-gradient(155deg,#072637 0,#0a3c49 58%,#095d5f 100%)!important;color:#c9ddda!important;margin-top:70px!important;border-top:0!important;position:relative;overflow:hidden}footer:before{content:"";position:absolute;width:480px;height:480px;border-radius:50%;right:-210px;top:-250px;background:radial-gradient(circle,rgba(244,180,95,.14),transparent 67%)}footer a{color:#e8f4f2!important}footer a:hover{color:#fff!important;text-decoration:underline}.footer-brand-row{padding-top:48px!important;border-bottom-color:rgba(255,255,255,.1)!important}.footer-brand-row>p{color:#bad3cf!important;max-width:650px}.footer-top{padding-top:30px!important;padding-bottom:32px!important}.footer-top h3{color:#fff!important;font-size:12px!important;letter-spacing:.08em!important;text-transform:uppercase!important}.footer-top a{font-size:13.5px!important}.footer-disclosure{border-color:rgba(255,255,255,.13)!important;background:rgba(255,255,255,.045)!important;border-radius:18px!important}.footer-disclosure strong{color:#fff!important}.footer-bottom{border-top-color:rgba(255,255,255,.1)!important}.footer-cert span{border-color:rgba(255,255,255,.17)!important;color:#cfe3df!important;background:rgba(255,255,255,.035)!important}

/* Home visual composition */
body[data-platform-page="/"] .home-hero{background:linear-gradient(135deg,#f3faf7 0,#fbf8ef 100%)!important;overflow:hidden!important}.home-hero-grid{position:relative}.v7-hero-visual{min-height:390px;display:flex;align-items:center;justify-content:center;position:relative}.v7-hero-orbit{position:relative;width:360px;height:330px;border-radius:48% 52% 47% 53%;background:radial-gradient(circle at center,#fff 0,#e4f3ef 52%,rgba(228,243,239,0) 73%)}.v7-choice-core{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:190px;height:180px;border-radius:30px;background:#fff;border:1px solid var(--v7-line);box-shadow:0 22px 55px rgba(11,48,68,.13);display:flex;align-items:center;justify-content:center;flex-direction:column;text-align:center;padding:16px}.v7-choice-core strong{font-size:15px;color:var(--v7-ink);margin-top:10px}.v7-choice-core small{font-size:10px;color:#70848a;margin-top:4px}.v7-choice-core .v7-logo-mark{width:66px;height:66px}.v7-orbit-card{position:absolute;background:#fff;border:1px solid var(--v7-line);border-radius:999px;padding:9px 14px;font-size:11px;font-weight:760;color:var(--v7-ink);box-shadow:0 8px 22px rgba(11,48,68,.09)}.v7-orbit-card.one{left:2px;top:62px}.v7-orbit-card.two{right:-2px;top:55px}.v7-orbit-card.three{left:12px;bottom:55px}.v7-orbit-card.four{right:0;bottom:63px}.v7-hero-orbit:before,.v7-hero-orbit:after{content:"";position:absolute;inset:40px;border:1px dashed rgba(8,120,111,.24);border-radius:50%;transform:rotate(12deg)}.v7-hero-orbit:after{inset:72px;transform:rotate(-14deg);border-color:rgba(244,180,95,.4)}

/* Share, breadcrumbs, sitemap and small states */
.platform-sharebar{margin-top:14px!important}.share-menu summary{border-radius:999px!important}.share-popover{border-radius:16px!important;box-shadow:var(--v7-shadow)!important}.crumbs{padding-top:16px!important;color:#71848a!important}.pathway-list{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important}.pathway-list li{border:1px solid var(--v7-line)!important;background:#fff!important;border-radius:12px!important;padding:11px 13px!important}.empty-state,.not-found{border-radius:24px!important;background:linear-gradient(145deg,#f0f8f5,#fff7e9)!important;border:1px solid var(--v7-line)!important}

/* Reduced motion */
@media (prefers-reduced-motion:reduce){.v7-category-card,.v7-product-card,.button,.brand-card,.guide-card{transition:none!important}.v7-category-card:hover,.v7-product-card:hover,.brand-card:hover,.guide-card:hover,.button:hover{transform:none!important}}

/* Laptop */
@media (max-width:1100px){.v7-logo-type small{display:none}.site-header .brand{min-width:210px}.mega-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important}.mega-feature{grid-column:1/-1!important;display:flex!important;align-items:center;justify-content:space-between}.premium-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.v7-hero-visual{min-height:330px}.v7-hero-orbit{transform:scale(.9)}body[data-platform-page="/decision-lab/"] .hero,body[data-platform-page="/my-apg/"] .hero{padding-right:38%!important}.v7-signature-illustration{min-width:245px;width:34%}}

/* Tablet */
@media (max-width:820px){.utility{display:none!important}.masthead{min-height:68px!important}.site-header .brand{min-width:0}.v7-logo-mark{width:43px;height:43px}.v7-logo-type strong{font-size:14px}.v7-logo-type small{display:none}.header-search{display:none!important}.primary-nav{display:none!important}.mobile-toggle{border-radius:12px!important}.mobile-nav{box-shadow:0 24px 55px rgba(7,38,53,.18)!important}.mobile-nav-inner{padding-top:15px!important;padding-bottom:24px!important}.mobile-section{border-radius:15px!important;border-color:var(--v7-line)!important}.mobile-section summary{min-height:51px!important}.premium-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:14px!important}.v7-category-card{grid-template-rows:145px 1fr!important}.v7-category-scene{min-height:145px;padding:15px}.v7-scene-icon{width:78px;height:78px}.pathway-list{grid-template-columns:repeat(2,minmax(0,1fr))!important}.hero{padding:30px!important}.v7-page-scene{float:none;width:100%;margin:0 0 22px}.v7-page-scene .v7-category-scene{min-height:145px}body[data-platform-page="/decision-lab/"] .hero,body[data-platform-page="/my-apg/"] .hero{padding-right:30px!important}.v7-signature-illustration{position:relative;right:auto;top:auto;width:100%;min-width:0;height:180px;margin:0 0 25px}.home-hero-grid{grid-template-columns:1fr!important}.v7-hero-visual{min-height:300px}.v7-hero-orbit{transform:scale(.82)}.footer-top{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:30px!important}}

/* Mobile */
@media (max-width:560px){body[data-platform-v7=true] .wrap{padding-inline:16px!important}.masthead{gap:10px!important}.v7-logo-type{display:none}.site-header .brand{width:45px}.v7-logo-mark{width:43px;height:43px}.header-actions .header-action span{display:none!important}.header-actions{gap:3px!important}.header-action{width:40px!important;height:40px!important;padding:8px!important}.mobile-toggle span{display:none!important}.global-search{min-height:48px!important}.global-search button{padding-inline:14px!important}.hero{padding:24px 20px!important;margin:15px 0!important;border-radius:21px}.hero h1{font-size:clamp(31px,10vw,43px)!important}.section{padding-top:38px!important;padding-bottom:38px!important}.section-head{align-items:flex-start!important}.premium-category-grid{grid-template-columns:1fr!important}.v7-category-card{grid-template-columns:126px 1fr!important;grid-template-rows:1fr!important;min-height:210px!important;padding:7px!important}.v7-category-scene{min-height:100%!important;height:100%;padding:10px;border-radius:17px}.v7-scene-icon{width:72px;height:72px;right:7px;top:10px}.v7-scene-copy{display:none}.v7-category-card-copy{padding:12px 11px!important}.v7-category-card-copy h3{font-size:18px!important;margin-bottom:5px!important}.v7-category-card-copy p:not(.eyebrow){font-size:12px!important;line-height:1.45!important;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.v7-category-card-copy .pills{display:none!important}.v7-category-card-copy .card-actions{display:flex!important;flex-direction:column!important;align-items:flex-start!important}.v7-category-card-copy .button{padding:8px 10px!important;font-size:11px!important}.v7-product-card .product-visual{min-height:190px!important}.product-card-body{padding:15px!important}.card-actions{flex-wrap:wrap!important}.card-actions .button{flex:1 1 120px}.pathway-list{grid-template-columns:1fr!important}.soft-panel{padding:19px!important;border-radius:20px!important}.v7-hero-visual{min-height:250px;overflow:hidden}.v7-hero-orbit{transform:scale(.68)}.difference-engine{border-radius:20px!important;margin-inline:-2px}.comparison-table{font-size:12px!important}.comparison-table th,.comparison-table td{padding:9px 7px!important}.footer-brand-row{display:block!important}.footer-brand-row .v7-logo-type{display:flex!important}.footer-top{grid-template-columns:1fr 1fr!important;gap:24px 14px!important}.footer-disclosure{display:block!important}.footer-disclosure>div+div{margin-top:17px}.footer-bottom{display:block!important}.footer-cert{margin-top:14px!important;display:flex!important;flex-wrap:wrap!important}.v7-page-scene{margin-bottom:15px}.v7-page-scene .v7-category-scene{min-height:120px}.v7-page-scene .v7-scene-copy{display:flex}.v7-page-scene .v7-scene-icon{width:72px;height:72px}.v7-signature-illustration{height:145px}.share-popover{right:0!important;left:auto!important;max-width:calc(100vw - 32px)!important}}
`;
module.exports={platformV7Css};
