const {categories,products}=require('../data');
const {brands,pairPages}=require('./routes');
const {direct}=require('../data/retailers-v6');
const {layout,hero,esc,categoryIcon}=require('./ui');

function evidenceLabel(c){return c.evidenceLabel||(c.evidenceTier==='deep'?'Deep evidence':'Starter evidence');}

function compareHub(req){
  const count=Object.keys(categories).length;
  const body=hero('Compare products','Build a comparison around the decision','Choose a category, add products to the shortlist and share the resulting 2–4 product comparison without creating an account.')+`<section class="section"><div class="section-head"><div><p class="kicker">All comparison hubs</p><h2>${count} populated categories</h2><p>Prepared editorial head-to-heads are deliberately limited. Dynamic shortlists remain noindex to avoid thin comparison permutations.</p></div></div><div class="platform-hub-grid">${Object.values(categories).map(c=>`<article class="platform-hub-card">${categoryIcon(c.icon)}<div><span class="evidence-chip evidence-${c.evidenceTier}">${esc(evidenceLabel(c))}</span><h3>${esc(c.label)}</h3><p>${c.products.length} maintained products · ${pairPages.filter(x=>x.category===c.slug).length} prepared head-to-heads</p><div class="actions"><a class="button compact" href="/compare/${c.slug}/">Compare</a><a class="text-link" href="/categories/${c.slug}/">Browse →</a></div></div></article>`).join('')}</div></section>`;
  return layout(req,{title:'Compare Products Australia | Australian Product Guide',description:`Build transparent product comparisons across ${count} maintained Australian Product Guide categories.`,path:'/compare/',body,crumbs:[{name:'Home',path:'/'},{name:'Compare',path:'/compare/'}]});
}

function guidesHub(req){
  const count=Object.keys(categories).length;
  const body=hero('Buying guides','Understand the category before the model','APG buying guides focus on the decisions that change suitability: budget, constraints, trade-offs and the factors worth comparing.')+`<section class="section"><div class="section-head"><div><p class="kicker">Decision-first guides</p><h2>${count} category guides</h2></div></div><div class="platform-hub-grid">${Object.values(categories).map(c=>`<article class="platform-hub-card">${categoryIcon(c.icon)}<div><span class="evidence-chip evidence-${c.evidenceTier}">${esc(evidenceLabel(c))}</span><h3><a href="/guides/${c.slug}-buying-guide/">${esc(c.label)}</a></h3><p>${esc(c.factors.slice(0,2).join(' · '))}</p><a class="text-link" href="/guides/${c.slug}-buying-guide/">Read guide →</a></div></article>`).join('')}</div></section>`;
  return layout(req,{title:'Australian Product Buying Guides | Australian Product Guide',description:`Decision-first Australian buying guides across APG’s ${count} maintained product categories.`,path:'/guides/',body,crumbs:[{name:'Home',path:'/'},{name:'Buying guides',path:'/guides/'}]});
}

function retailersHub(req){
  const exact=Object.keys(direct).length,fallback=Math.max(0,products.length-exact),manufacturer=products.filter(p=>/Official Australian manufacturer/i.test(p.sourceType||'')).length;
  const body=hero('Retailer discovery','Retailer links are a pathway, not a ranking signal','APG separates product suitability from where a product can be bought. Commission and retailer availability contribute zero recommendation points.')+`<section class="section"><div class="wrap trust-story"><div><p class="kicker">Evidence and commerce are separate</p><h2>${manufacturer} products now carry exact Australian manufacturer evidence</h2><p>Manufacturer and support sources establish product identity and maintained decision facts. Retailer links are then provided as a separate shopping pathway, so a retailer cannot earn a higher recommendation score by paying more commission.</p><p>For Amazon Australia, ${exact} maintained products have independently verified individual product destinations. The remaining ${fallback} use transparent model-specific Amazon search fallbacks rather than guessed ASINs.</p></div><div class="trust-visual"><div><strong>${manufacturer}</strong><span>manufacturer-verified product records</span></div><div><strong>${exact}</strong><span>verified exact Amazon links</span></div><div><strong>0</strong><span>commercial scoring points</span></div><div><strong>Rights-first</strong><span>image provenance gate</span></div></div></div></section><section class="section soft-section full-bleed"><div class="wrap"><div class="section-head"><div><p class="kicker">Multi-retailer roadmap</p><h2>Broader Australian retailer coverage without retailer-driven rankings.</h2><p>APG is structured to add exact Australian retailer paths from major electronics, appliance, office and specialist retailers where the exact model and offer can be verified. Until then, it will not fabricate price comparison or imply whole-of-market coverage.</p></div></div><div class="grid three"><article class="feature-card"><p class="eyebrow">Current</p><h3>Exact manufacturer evidence</h3><p>Primary Australian product and support pages are preferred for specifications and variant identity.</p></article><article class="feature-card"><p class="eyebrow">Current</p><h3>Amazon exact + safe fallback</h3><p>Verified individual links where identity is certain; model-search fallback where it is not.</p></article><article class="feature-card"><p class="eyebrow">Planned</p><h3>Multi-retailer exact paths</h3><p>JB Hi-Fi, The Good Guys, Officeworks, Appliances Online and other relevant retailers can be added only after exact-model verification and commercial/legal review.</p></article></div></div></section>`;
  return layout(req,{title:'Retailer Discovery & Australian Product Evidence | Australian Product Guide',description:'How APG separates manufacturer evidence, exact retailer paths, Amazon Australia affiliate attribution, image provenance and recommendation neutrality.',path:'/retailers/',body,crumbs:[{name:'Home',path:'/'},{name:'Retailers',path:'/retailers/'}]});
}

module.exports={compareHub,guidesHub,retailersHub};
