const platformV5Css=`
/* APG Platform v5 — premium consumer discovery layer. HTML/CSS first, no framework. */
:root{--v5-ink:#0d2b3e;--v5-teal:#08786f;--v5-mint:#dff3ed;--v5-cream:#fbf7ed;--v5-gold:#d49a42;--v5-line:rgba(13,43,62,.11);--v5-shadow:0 18px 55px rgba(13,43,62,.10);--v5-shadow-lg:0 28px 90px rgba(13,43,62,.14)}
body[data-platform-v5="true"]{background:linear-gradient(180deg,#fff 0,#fbfcfb 42%,#fff 100%);color:var(--v5-ink)}
body[data-platform-v5="true"] .site-header{box-shadow:0 1px 0 rgba(13,43,62,.07);background:rgba(255,255,255,.97);backdrop-filter:saturate(150%) blur(14px)}
body[data-platform-v5="true"] .utility{background:#0b293b;color:#eaf5f2}body[data-platform-v5="true"] .utility a{color:#fff}
body[data-platform-v5="true"] .masthead{min-height:86px;gap:1.5rem}body[data-platform-v5="true"] .logo-mark{width:48px;height:48px;filter:drop-shadow(0 9px 16px rgba(8,120,111,.17))}body[data-platform-v5="true"] .logo-copy strong{font-size:1.02rem;letter-spacing:-.02em}body[data-platform-v5="true"] .logo-copy small{font-size:.69rem;color:#63727c}
body[data-platform-v5="true"] .header-search{max-width:760px;flex:1}body[data-platform-v5="true"] .global-search{border:1px solid rgba(13,43,62,.14);border-radius:17px;box-shadow:0 10px 28px rgba(13,43,62,.07);background:#fff}body[data-platform-v5="true"] .global-search:focus-within{border-color:rgba(8,120,111,.65);box-shadow:0 0 0 4px rgba(8,120,111,.10),0 14px 34px rgba(13,43,62,.08)}body[data-platform-v5="true"] .global-search input{font-size:.96rem}body[data-platform-v5="true"] .global-search button{border-radius:12px;margin:5px;background:#0d3d50}
body[data-platform-v5="true"] .primary-nav{border-top:1px solid rgba(13,43,62,.06);border-bottom:1px solid rgba(13,43,62,.08)}body[data-platform-v5="true"] .nav-inner>a,body[data-platform-v5="true"] .nav-trigger{min-height:48px;font-weight:790}body[data-platform-v5="true"] .nav-inner>a:hover,body[data-platform-v5="true"] .nav-inner>a:focus-visible,body[data-platform-v5="true"] .nav-trigger:hover,body[data-platform-v5="true"] .nav-trigger:focus-visible{color:var(--v5-teal);background:#f0f8f5}
body[data-platform-v5="true"] .platform-mega{border:1px solid var(--v5-line);border-radius:0 0 26px 26px;box-shadow:var(--v5-shadow-lg);padding:1.1rem;background:rgba(255,255,255,.985)}body[data-platform-v5="true"] .mega-group{padding:.4rem}body[data-platform-v5="true"] .mega-group>a{border-radius:12px;padding:.64rem .7rem}body[data-platform-v5="true"] .mega-group>a:hover,body[data-platform-v5="true"] .mega-group>a:focus-visible{background:#edf7f4;transform:translateX(2px)}body[data-platform-v5="true"] .mega-title{font-size:.69rem;letter-spacing:.08em;color:#72818a}body[data-platform-v5="true"] .mega-feature{border-radius:22px;overflow:hidden;box-shadow:0 15px 38px rgba(13,43,62,.15)}
body[data-platform-v5="true"] .search-suggestions{top:calc(100% + 9px);border:1px solid var(--v5-line);border-radius:20px;box-shadow:var(--v5-shadow-lg);padding:.55rem;max-height:min(68vh,560px);overflow:auto;background:#fff;z-index:90}body[data-platform-v5="true"] .search-suggestions [role="option"],body[data-platform-v5="true"] .search-suggestions a{border-radius:13px;padding:.72rem .8rem}body[data-platform-v5="true"] .search-suggestions [role="option"]:hover,body[data-platform-v5="true"] .search-suggestions [role="option"][aria-selected="true"],body[data-platform-v5="true"] .search-suggestions a:hover{background:#edf7f4}
.v5-hero-upgrade{position:relative;overflow:hidden;background:radial-gradient(circle at 88% 20%,rgba(72,191,170,.25),transparent 28%),radial-gradient(circle at 72% 82%,rgba(212,154,66,.18),transparent 30%),linear-gradient(140deg,#f8fbfa,#edf7f4 62%,#fff8ec);border-bottom:1px solid rgba(13,43,62,.08)}.v5-hero-upgrade:after{content:"";position:absolute;width:360px;height:360px;border:1px solid rgba(8,120,111,.12);border-radius:50%;right:-80px;top:-130px;box-shadow:0 0 0 44px rgba(8,120,111,.035),0 0 0 88px rgba(8,120,111,.025)}
.v5-home-band{padding:clamp(2.5rem,6vw,5.2rem) 0}.v5-home-band .section-head{display:flex;justify-content:space-between;align-items:end;gap:2rem;margin-bottom:1.5rem}.v5-home-band h2{font-size:clamp(1.65rem,3vw,2.55rem);letter-spacing:-.035em;margin:.25rem 0}.v5-home-band p{color:#5b6c76;max-width:760px}.v5-journey{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.85rem;counter-reset:step}.v5-step{counter-increment:step;position:relative;padding:1.15rem;border:1px solid var(--v5-line);border-radius:20px;background:#fff;box-shadow:0 10px 28px rgba(13,43,62,.055)}.v5-step:before{content:counter(step);display:grid;place-items:center;width:31px;height:31px;border-radius:10px;background:#0d3d50;color:#fff;font-weight:900;margin-bottom:.8rem}.v5-step strong{display:block;margin-bottom:.3rem}.v5-step span{font-size:.82rem;color:#697983;line-height:1.5}.v5-step:not(:last-child):after{content:"→";position:absolute;right:-.67rem;top:1.3rem;z-index:2;color:#789099;font-weight:900}
.v5-need-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:.8rem}.v5-need{display:flex;min-height:112px;flex-direction:column;justify-content:space-between;padding:1rem;border:1px solid var(--v5-line);border-radius:20px;text-decoration:none;color:var(--v5-ink);background:linear-gradient(145deg,#fff,#f7faf9);box-shadow:0 9px 25px rgba(13,43,62,.045);transition:.2s ease}.v5-need:hover,.v5-need:focus-visible{transform:translateY(-3px);box-shadow:var(--v5-shadow);border-color:rgba(8,120,111,.28)}.v5-need b{font-size:.92rem}.v5-need small{color:#6b7b85}.v5-need-icon{width:37px;height:37px;border-radius:13px;background:linear-gradient(135deg,#0d3d50,#08786f);box-shadow:inset 0 0 0 1px rgba(255,255,255,.15),0 8px 16px rgba(8,120,111,.16);position:relative}.v5-need-icon:after{content:"";position:absolute;left:10px;top:10px;width:17px;height:17px;border:2px solid rgba(255,255,255,.88);border-radius:5px;transform:rotate(12deg)}
.v5-trust-grid{display:grid;grid-template-columns:1.2fr repeat(3,1fr);gap:1rem}.v5-trust-card{padding:1.25rem;border-radius:22px;border:1px solid var(--v5-line);background:#fff}.v5-trust-card:first-child{background:linear-gradient(145deg,#0d3045,#075f5c);color:white}.v5-trust-card:first-child p{color:rgba(255,255,255,.78)}.v5-trust-card strong{font-size:1.45rem;display:block;margin-bottom:.35rem}.v5-trust-card span,.v5-trust-card p{font-size:.86rem;color:#647681}
/* Deliberate APG illustration system. Never presented as an exact-product photograph. */
body[data-platform-v5="true"] .product-visual{background:linear-gradient(145deg,#f8fbfa,#eef6f3);border:1px solid rgba(13,43,62,.07);border-radius:22px;overflow:hidden;box-shadow:inset 0 1px 0 rgba(255,255,255,.8)}body[data-platform-v5="true"] .product-visual .product-art{position:relative;min-height:152px;background:radial-gradient(circle at 65% 36%,rgba(255,255,255,.82),transparent 28%),linear-gradient(135deg,rgba(8,120,111,.09),rgba(13,61,80,.03))}body[data-platform-v5="true"] .product-visual .product-art:before{content:"";position:absolute;left:50%;top:48%;width:72px;height:72px;transform:translate(-50%,-50%);border:3px solid rgba(13,61,80,.53);border-radius:22px 22px 28px 28px;box-shadow:14px 12px 0 rgba(8,120,111,.10),-12px -10px 0 rgba(212,154,66,.08)}body[data-platform-v5="true"] .product-visual .product-art:after{content:"APG ILLUSTRATION";position:absolute;left:12px;bottom:10px;font-size:.58rem;letter-spacing:.09em;font-weight:900;color:rgba(13,43,62,.48)}body[data-platform-v5="true"] .product-visual .category-icon{opacity:0!important}body[data-platform-v5="true"] .product-visual .art-model{position:absolute;z-index:3;right:12px;top:12px;font-size:.64rem;text-transform:uppercase;letter-spacing:.07em;font-weight:900;background:rgba(255,255,255,.87);border:1px solid rgba(13,43,62,.08);padding:.3rem .48rem;border-radius:999px}
body[data-platform-v5="true"] .product-visual[data-product-category*="headphone"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category="earbuds"] .product-art:before{width:66px;height:58px;border-radius:36px 36px 18px 18px;border-bottom-color:transparent}
body[data-platform-v5="true"] .product-visual[data-product-category*="vacuum"] .product-art:before{width:76px;height:76px;border-radius:50%;box-shadow:0 16px 0 -11px rgba(13,61,80,.45),14px 12px 0 rgba(8,120,111,.08)}
body[data-platform-v5="true"] .product-visual[data-product-category*="monitor"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category="projectors"] .product-art:before{width:92px;height:56px;border-radius:9px;box-shadow:0 18px 0 -15px rgba(13,61,80,.55),0 28px 0 -24px rgba(13,61,80,.5)}
body[data-platform-v5="true"] .product-visual[data-product-category*="chair"] .product-art:before{width:62px;height:72px;border-radius:28px 28px 15px 15px;transform:translate(-50%,-50%) rotate(-3deg)}
body[data-platform-v5="true"] .product-visual[data-product-category*="desk"] .product-art:before{width:92px;height:42px;border-radius:8px;box-shadow:-28px 46px 0 -25px rgba(13,61,80,.5),28px 46px 0 -25px rgba(13,61,80,.5)}
body[data-platform-v5="true"] .product-visual[data-product-category*="camera"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="doorbell"] .product-art:before{width:54px;height:78px;border-radius:18px;box-shadow:inset 0 0 0 16px rgba(8,120,111,.055)}
body[data-platform-v5="true"] .product-visual[data-product-category*="power"] .product-art:before{width:76px;height:68px;border-radius:16px;box-shadow:inset 0 0 0 18px rgba(8,120,111,.055),14px 12px 0 rgba(212,154,66,.08)}
body[data-platform-v5="true"] .product-visual[data-product-category="luggage"] .product-art:before{width:58px;height:78px;border-radius:15px;box-shadow:0 -13px 0 -9px rgba(13,61,80,.5),14px 12px 0 rgba(8,120,111,.08)}
body[data-platform-v5="true"] .product-visual[data-product-category*="keyboard"] .product-art:before{width:98px;height:47px;border-radius:9px;background:repeating-linear-gradient(90deg,transparent 0 9px,rgba(13,61,80,.1) 9px 11px)}
body[data-platform-v5="true"] .product-visual[data-product-category*="mouse"] .product-art:before{width:52px;height:76px;border-radius:28px}
body[data-platform-v5="true"] .product-visual[data-product-category*="watch"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="tracker"] .product-art:before{width:48px;height:62px;border-radius:17px;box-shadow:0 -31px 0 -24px rgba(13,61,80,.48),0 31px 0 -24px rgba(13,61,80,.48)}
body[data-platform-v5="true"] .product-visual[data-product-category*="speaker"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category="soundbars"] .product-art:before{width:96px;height:40px;border-radius:20px;background:radial-gradient(circle,rgba(13,61,80,.18) 1px,transparent 1.5px) 0 0/8px 8px}
body[data-platform-v5="true"] .product-visual[data-product-category*="toothbrush"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="shaver"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="dryer"] .product-art:before{width:38px;height:86px;border-radius:18px}
body[data-platform-v5="true"] .product-visual[data-product-category*="blender"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="mixer"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="cooker"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="fryer"] .product-art:before,body[data-platform-v5="true"] .product-visual[data-product-category*="coffee"] .product-art:before{width:66px;height:78px;border-radius:18px 18px 25px 25px}
body[data-platform-v5="true"] .visual-copy small{font-size:.69rem;color:#75848d}.image-provenance{font-size:.65rem;color:#677984;background:#f6f8f7;border-radius:8px;padding:.28rem .45rem}
body[data-platform-v5="true"] .product-card,body[data-platform-v5="true"] .editorial-card,body[data-platform-v5="true"] .category-card,body[data-platform-v5="true"] .workspace-panel{border:1px solid var(--v5-line);border-radius:24px;box-shadow:0 10px 32px rgba(13,43,62,.055);transition:transform .2s ease,box-shadow .2s ease,border-color .2s ease}body[data-platform-v5="true"] .product-card:hover,body[data-platform-v5="true"] .category-card:hover,body[data-platform-v5="true"] .editorial-card:hover{transform:translateY(-3px);box-shadow:var(--v5-shadow);border-color:rgba(8,120,111,.23)}
body[data-platform-v5="true"] .retailer-card,body[data-platform-v5="true"] .retailer-row{border-radius:20px;border:1px solid var(--v5-line);background:#fff;box-shadow:0 9px 24px rgba(13,43,62,.05)}body[data-platform-v5="true"] .retailer-card .button,body[data-platform-v5="true"] #where-to-buy .button{min-height:44px}
body[data-platform-v5="true"] .policy-page,body[data-platform-v5="true"] .trust-page{max-width:1180px} .v5-policy-toc{position:relative;padding:1rem 1.15rem;border:1px solid var(--v5-line);border-radius:20px;background:#f7faf9;margin:1.25rem 0 2rem}.v5-policy-toc strong{display:block;margin-bottom:.6rem}.v5-policy-toc div{display:flex;flex-wrap:wrap;gap:.45rem}.v5-policy-toc a{font-size:.78rem;text-decoration:none;background:#fff;border:1px solid rgba(13,43,62,.09);border-radius:999px;padding:.38rem .6rem;color:#274759}.v5-policy-toc a:hover,.v5-policy-toc a:focus-visible{border-color:rgba(8,120,111,.45);color:#06685f}
.v5-account-status{margin:1.3rem 0;padding:1.2rem;border-radius:22px;background:linear-gradient(135deg,#edf8f5,#fff);border:1px solid rgba(8,120,111,.18);display:grid;grid-template-columns:1.25fr .75fr;gap:1rem}.v5-account-status strong{display:block;font-size:1.08rem;margin-bottom:.35rem}.v5-account-status p{margin:0;color:#60727d}.v5-account-badge{align-self:center;justify-self:end;padding:.55rem .75rem;border-radius:999px;background:#dff3ed;color:#08645f;font-weight:850;font-size:.78rem}
.v5-sitemap-intro{padding:1.2rem;border:1px solid var(--v5-line);border-radius:22px;background:linear-gradient(135deg,#f7fbfa,#fff8ef);margin-bottom:1rem}
body[data-platform-v5="true"] footer{background:#0b293b;color:#e9f3f1;margin-top:4rem}body[data-platform-v5="true"] footer a{color:#e9f3f1}body[data-platform-v5="true"] footer h3{color:#fff}body[data-platform-v5="true"] footer .footer-brand-row p,body[data-platform-v5="true"] footer .footer-disclosure span,body[data-platform-v5="true"] footer .footer-bottom{color:#bdd0cc}body[data-platform-v5="true"] footer .logo-copy strong{color:#fff}body[data-platform-v5="true"] footer .logo-copy small{color:#bdd0cc}.v5-footer-link{font-weight:800;color:#bfe9df!important}
:focus-visible{outline:3px solid rgba(8,120,111,.62);outline-offset:3px}button,a,input,summary{scroll-margin-top:120px}
@media(max-width:1100px){.v5-journey{grid-template-columns:repeat(3,1fr)}.v5-need-grid{grid-template-columns:repeat(3,1fr)}.v5-trust-grid{grid-template-columns:1fr 1fr}.v5-step:nth-child(3):after{display:none}}
@media(max-width:760px){body[data-platform-v5="true"] .utility{display:none}body[data-platform-v5="true"] .masthead{min-height:68px;padding-top:.6rem;padding-bottom:.6rem}.logo-copy small{display:none}body[data-platform-v5="true"] .logo-mark{width:40px;height:40px}body[data-platform-v5="true"] .mobile-nav{background:#fff}body[data-platform-v5="true"] .mobile-nav-inner{padding-top:.7rem;padding-bottom:1.2rem}.v5-home-band{padding:2.7rem 0}.v5-home-band .section-head{align-items:start;flex-direction:column;gap:.6rem}.v5-journey{grid-template-columns:1fr}.v5-step:after{display:none!important}.v5-need-grid{grid-template-columns:1fr 1fr}.v5-trust-grid{grid-template-columns:1fr}.v5-account-status{grid-template-columns:1fr}.v5-account-badge{justify-self:start}.product-card .actions,.actions{flex-wrap:wrap}.button,.secondary-button{min-height:44px}.search-suggestions{position:fixed!important;left:10px!important;right:10px!important;top:76px!important;max-height:70vh!important;width:auto!important}}
@media(max-width:430px){.v5-need-grid{grid-template-columns:1fr}.v5-need{min-height:92px}.logo-copy strong{font-size:.88rem}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
`;
module.exports={platformV5Css};