const platformV3Css=`
/* APG Platform v3 — catalogue scale, sharing, evidence depth and workspace */
.platform-sharebar{display:flex;justify-content:flex-end;align-items:center;gap:.7rem;padding-top:1rem;position:relative;z-index:8}.share-context{font-size:.78rem;color:var(--muted,#63717c);font-weight:700;letter-spacing:.02em}.share-menu{position:relative}.share-menu>summary{list-style:none;cursor:pointer;border:1px solid rgba(16,47,74,.14);background:#fff;border-radius:999px;padding:.62rem .9rem;font-weight:800;color:#102f4a;box-shadow:0 8px 24px rgba(16,47,74,.08)}.share-menu>summary::-webkit-details-marker{display:none}.share-popover{position:absolute;right:0;top:calc(100% + .55rem);width:220px;background:#fff;border:1px solid rgba(16,47,74,.12);border-radius:18px;padding:.55rem;box-shadow:0 20px 60px rgba(16,47,74,.18);display:grid;gap:.25rem}.share-popover button{border:0;background:transparent;text-align:left;padding:.7rem .75rem;border-radius:12px;color:#18364c;font:inherit;cursor:pointer}.share-popover button:hover,.share-popover button:focus-visible{background:#edf7f5}.share-popover [data-share-status]{font-size:.76rem;color:#5d6d78;padding:.35rem .75rem}.share-card{width:38px;height:38px;border-radius:12px;border:1px solid rgba(16,47,74,.12);background:#fff;color:#173a52;font-size:1rem;cursor:pointer}.share-card:hover,.share-card:focus-visible{background:#edf7f5;border-color:rgba(8,120,111,.28)}
.platform-mega{max-height:min(76vh,690px);overflow:auto}.platform-mega .mega-grid{grid-template-columns:repeat(4,minmax(0,1fr)) minmax(230px,1.15fr)}.platform-mega .mega-feature{background:linear-gradient(145deg,#0f314a,#0b6f6a);color:white}.platform-mega .mega-feature .kicker{color:#aee6dd}.platform-mega .mega-feature p{color:rgba(255,255,255,.78)}.mobile-power{display:flex;justify-content:space-between;align-items:center;margin:.6rem 0 1rem;padding:1rem 1.1rem;border-radius:16px;background:linear-gradient(135deg,#10344f,#08786f);color:#fff!important;font-weight:850;text-decoration:none}
.evidence-chip,.evidence-deep,.evidence-starter{display:inline-flex;align-items:center;gap:.35rem;border-radius:999px;padding:.34rem .62rem;font-size:.72rem;font-weight:850;letter-spacing:.02em}.evidence-chip.evidence-deep,.evidence-deep{background:#e5f5f0;color:#07665f}.evidence-chip.evidence-starter,.evidence-starter{background:#fff4dd;color:#815b12}.independence-badge.evidence-deep,.independence-badge.evidence-starter{white-space:normal;text-align:right;max-width:320px}
.product-visual[data-evidence-tier="starter"]{position:relative;overflow:hidden}.product-visual[data-evidence-tier="starter"] .category-icon{opacity:0}.product-visual[data-evidence-tier="starter"]:before{content:attr(data-category-label);position:absolute;left:14px;top:14px;z-index:3;padding:.35rem .58rem;border-radius:999px;background:rgba(255,255,255,.9);backdrop-filter:blur(7px);font-size:.67rem;font-weight:900;letter-spacing:.04em;text-transform:uppercase;color:#16384e;box-shadow:0 5px 18px rgba(16,47,74,.09)}.product-visual[data-evidence-tier="starter"] .product-art:after{content:'APG';position:absolute;inset:0;display:grid;place-items:center;font-size:clamp(1.1rem,2vw,1.7rem);font-weight:950;letter-spacing:.16em;color:rgba(16,47,74,.5)}
.freshness-section{padding-top:.5rem}.freshness-panel{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(360px,.9fr);gap:2rem;padding:clamp(1.25rem,3vw,2.25rem);border-radius:28px;background:linear-gradient(145deg,#f3faf8,#f8f6ef);border:1px solid rgba(8,120,111,.12)}.freshness-panel h2{margin:.3rem 0 .7rem}.freshness-panel dl{margin:0;display:grid;grid-template-columns:1fr 1fr;gap:.65rem}.freshness-panel dl>div{background:rgba(255,255,255,.82);border:1px solid rgba(16,47,74,.08);border-radius:15px;padding:.8rem}.freshness-panel dt{font-size:.7rem;text-transform:uppercase;letter-spacing:.055em;color:#667781;font-weight:850}.freshness-panel dd{margin:.25rem 0 0;font-weight:800;color:#16384e;font-size:.88rem}
.platform-hub-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.platform-hub-card{display:flex;align-items:flex-start;gap:1rem;padding:1.15rem;border:1px solid rgba(16,47,74,.1);border-radius:22px;background:#fff;box-shadow:0 10px 30px rgba(16,47,74,.055)}.platform-hub-card .category-icon{flex:0 0 auto}.platform-hub-card h3{margin:.42rem 0 .36rem;font-size:1.05rem}.platform-hub-card p{font-size:.85rem;color:#61717c;margin:.25rem 0 .8rem}.platform-hub-card .actions{gap:.65rem;margin:0}
.account-readiness{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(180px,.55fr) minmax(180px,.55fr);gap:1rem;align-items:stretch}.account-readiness>div:first-child{padding-right:1.2rem}.account-state{padding:1.1rem;border-radius:20px;background:#fff;border:1px solid rgba(8,120,111,.15);display:flex;flex-direction:column;gap:.45rem}.account-state>span{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;font-weight:900;color:#08786f}.account-state strong{color:#16384e}.account-state small{color:#657680;line-height:1.5}.account-state.planned{border-style:dashed;background:rgba(255,255,255,.58)}.workspace-more{margin-top:0}.future-panel{background:linear-gradient(145deg,#f7f8fa,#f5f3ed)}.platform-policy-note{border:1px solid rgba(16,47,74,.1);border-radius:24px;padding:1.35rem;background:#f8faf9}.platform-policy-note h2{margin:.25rem 0 .5rem;font-size:1.25rem}
body[data-platform-page="/"] .premium-category-grid>.category-card:nth-child(n+13),body[data-platform-page="/"] .finder-launches>.finder-launch:nth-child(n+9),body[data-platform-page="/"] .guide-card-grid>.editorial-card:nth-child(n+9){display:none}.category-grid.premium-category-grid{align-items:stretch}.pathway-list{columns:3;column-gap:1.25rem}.pathway-list li{break-inside:avoid}.trust-strip strong{font-variant-numeric:tabular-nums}
@media(max-width:1100px){.platform-mega .mega-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.platform-mega .mega-feature{grid-column:span 3}.platform-hub-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.freshness-panel{grid-template-columns:1fr}.account-readiness{grid-template-columns:1fr 1fr}.account-readiness>div:first-child{grid-column:1/-1}.pathway-list{columns:2}}
@media(max-width:720px){.platform-sharebar{justify-content:space-between;padding-top:.75rem}.share-context{font-size:.72rem}.share-popover{position:fixed;left:14px;right:14px;bottom:14px;top:auto;width:auto;z-index:50}.platform-hub-grid{grid-template-columns:1fr}.platform-hub-card{padding:1rem}.freshness-panel{padding:1rem;border-radius:20px}.freshness-panel dl{grid-template-columns:1fr}.account-readiness{grid-template-columns:1fr}.account-readiness>div:first-child{grid-column:auto}.pathway-list{columns:1}body[data-platform-page="/"] .premium-category-grid>.category-card:nth-child(n+9){display:none}}
`;
module.exports={platformV3Css};