const {categories,products}=require('../data');
const {brands,pairPages}=require('./routes');
const {direct}=require('../data/retailers');
const {layout,hero,esc,categoryIcon}=require('./ui');

function compareHub(req){
  const body=hero('Compare products','Build a comparison around the decision','Choose a category, add products to the shortlist and share the resulting 2–4 product comparison without creating an account.')+`<section class="section"><div class="section-head"><div><p class="kicker">All comparison hubs</p><h2>${Object.keys(categories).length} populated categories</h2><p>Prepared editorial head-to-heads are deliberately limited. Dynamic shortlists remain noindex to avoid thin comparison permutations.</p></div></div><div class="platform-hub-grid">${Object.values(categories).map(c=>`<article class="platform-hub-card">${categoryIcon(c.icon)}<div><span class="evidence-chip evidence-${c.evidenceTier}">${c.evidenceTier==='deep'?'Deep evidence':'Starter evidence'}</span><h3>${esc(c.label)}</h3><p>${c.products.length} maintained products · ${pairPages.filter(x=>x.category===c.slug).length} prepared head-to-heads</p><div class="actions"><a class="button compact" href="/compare/${c.slug}/">Compare</a><a class="text-link" href="/categories/${c.slug}/">Browse →</a></div></div></article>`).join('')}</div></section>`;
  return layout(req,{title:'Compare Products Australia | Australian Product Guide',description:'Build transparent product comparisons across 48 Australian Product Guide categories.',path:'/compare/',body,crumbs:[{name:'Home',path:'/'},{name:'Compare',path:'/compare/'}]});
}

function guidesHub(req){
  const body=hero('Buying guides','Understand the category before the model','APG buying guides focus on the decisions that change suitability: budget, constraints, trade-offs and the factors worth comparing.')+`<section class="section"><div class="section-head"><div><p class="kicker">Decision-first guides</p><h2>${Object.keys(categories).length} category guides</h2></div></div><div class="platform-hub-grid">${Object.values(categories).map(c=>`<article class="platform-hub-card">${categoryIcon(c.icon)}<div><span class="evidence-chip evidence-${c.evidenceTier}">${c.evidenceTier==='deep'?'Deep evidence':'Starter evidence'}</span><h3><a href="/guides/${c.slug}-buying-guide/">${esc(c.label)}</a></h3><p>${esc(c.factors.slice(0,2).join(' · '))}</p><a class="text-link" href="/guides/${c.slug}-buying-guide/">Read guide →</a></div></article>`).join('')}</div></section>`;
  return layout(req,{title:'Australian Product Buying Guides | Australian Product Guide',description:'Decision-first Australian buying guides across APG’s maintained product categories.',path:'/guides/',body,crumbs:[{name:'Home',path:'/'},{name:'Buying guides',path:'/guides/'}]});
}

function retailersHub(req){
  const exact=Object.keys(direct).length,fallback=products.length-exact;
  const body=hero('Retailer discovery','Retailer links are a pathway, not a ranking signal','APG separates product suitability from where a product can be bought. Commission and retailer availability contribute zero recommendation points.')+`<section class="section"><div class="wrap trust-story"><div><p class="kicker">Amazon Australia</p><h2>${exact} exact individual product links verified</h2><p>${fallback} maintained products currently use transparent model-specific Amazon Australia search fallbacks rather than guessed ASINs. Every eligible Amazon destination carries APG’s Associates attribution.</p><p>Amazon product photography is not scraped. APG will only display Amazon Product Advertising Content after an authorised Amazon mechanism is connected and the returned identifier matches the verified product.</p></div><div class="trust-visual"><div><strong>${exact}</strong><span>verified exact Amazon links</span></div><div><strong>${fallback}</strong><span>model-search fallbacks</span></div><div><strong>0</strong><span>commercial scoring points</span></div><div><strong>Rights-first</strong><span>image provenance gate</span></div></div></div></section><section class="section soft-section full-bleed"><div class="wrap"><div class="section-head"><div><p class="kicker">Retailer roadmap</p><h2>Amazon is useful, but APG should not depend on one retailer.</h2><p>The next commercial-data phase should expand exact Australian retailer coverage, availability and lawful imagery feeds while preserving recommendation neutrality.</p></div></div></div></section>`;
  return layout(req,{title:'Retailer Discovery & Amazon Australia | Australian Product Guide',description:'How APG handles Amazon Australia, exact product links, affiliate attribution, image provenance and retailer neutrality.',path:'/retailers/',body,crumbs:[{name:'Home',path:'/'},{name:'Retailers',path:'/retailers/'}]});
}

module.exports={compareHub,guidesHub,retailersHub};