const js=`(()=>{
const launcher=document.getElementById('apgAssistantLauncher'),panel=document.getElementById('apgAssistantPanel'),body=document.getElementById('apgAssistantBody');if(!launcher||!panel||!body)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number(n||0).toLocaleString('en-AU'),human=s=>String(s||'').split('-').join(' ').split(' ').filter(Boolean).map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');
const state={busy:false,last:null,decisionState:null,budget:null,category:null};
const brand=panel.querySelector('.apg-assistant-brand');if(brand){const copy=brand.querySelector('span:last-child');if(copy)copy.innerHTML='<strong>Scout · Australian Product Guide</strong><small>Personal buying help, powered by APG research</small>';}
const foot=panel.querySelector('.apg-assistant-foot');if(foot)foot.innerHTML='<strong>Independent match.</strong> Scout follows your needs and APG research. Retailer payments never change the recommendation order.';
panel.setAttribute('aria-label','Scout Australian Product Guide shopping assistant');
function bot(t){return '<div class="scout-row"><div class="scout-bubble">'+t+'</div></div>'}function user(t){return '<div class="scout-row user"><div class="scout-bubble">'+esc(t)+'</div></div>'}
function thread(){let t=body.querySelector('.scout-thread');if(!t){body.innerHTML='<div class="scout-thread"></div>';t=body.querySelector('.scout-thread')}return t;}
function pageContext(){const path=location.pathname,h1=(document.querySelector('main h1')?.textContent||'').trim(),parts=path.split('/').filter(Boolean);let category=null;const visual=document.querySelector('[data-product-category]');if(visual?.dataset.productCategory)category=visual.dataset.productCategory;if(!category&&parts[0]==='categories')category=parts[1]||null;const product=parts[0]==='products'?h1:null;return {path,h1,category,product};}
const quick=[
 {label:'TVs',detail:'Movies, sport & gaming',category:'televisions',q:'TV for my room and budget'},
 {label:'Laptops',detail:'Work, study & travel',category:'laptops',q:'laptop for work study and travel'},
 {label:'Phones',detail:'Camera, battery & value',category:'smartphones',q:'smartphone with great camera battery and value'},
 {label:'Washing machines',detail:'Capacity & convenience',category:'washing-machines',q:'washing machine for my household'},
 {label:'Robot vacuums',detail:'Pets, mopping & docks',category:'robot-vacuums',q:'robot vacuum for pet hair and mopping'},
 {label:'Coffee machines',detail:'Flat whites & easy use',category:'coffee-machines',q:'coffee machine for flat whites and easy daily use'}
];
function contextCard(){const c=pageContext();if(c.product&&c.category)return '<button class="scout-context" type="button" data-scout-q="best alternatives for '+esc(c.product)+'" data-scout-category="'+esc(c.category)+'"><span>Looking at this product?</span><strong>Find the best alternatives to '+esc(c.product)+'</strong><small>I’ll keep the comparison inside this category.</small></button>';if(c.h1&&c.category)return '<button class="scout-context" type="button" data-scout-q="help me choose the best option for my needs" data-scout-category="'+esc(c.category)+'"><span>Shopping this category?</span><strong>Help me choose from '+esc(c.h1)+'</strong><small>Tell me your budget and priorities in your next message.</small></button>';return '';}
function welcome(){state.last=null;state.decisionState=null;state.budget=null;state.category=null;body.innerHTML='<div class="scout-thread">'+bot('<span class="scout-kicker">Your personal buying guide</span><strong class="scout-hello">What are you shopping for?</strong><span class="scout-intro">Tell me the product, budget, what matters most and anything you refuse to compromise on. I’ll narrow the options and explain the trade-offs.</span>')+contextCard()+'<section class="scout-start"><div class="scout-start-head"><strong>Popular starting points</strong><span>Or type anything below</span></div><div class="scout-chips">'+quick.map(x=>'<button class="scout-chip" type="button" data-scout-q="'+esc(x.q)+'" data-scout-category="'+esc(x.category)+'"><span>'+esc(x.label)+'</span><small>'+esc(x.detail)+'</small></button>').join('')+'</div></section><div class="scout-trustline"><span aria-hidden="true">✓</span><span>No sponsored ranking. No generic “winner”. Just the best fit APG can support from the evidence it maintains.</span></div></div>';}
function ensureComposer(){if(panel.querySelector('.scout-composer'))return;const c=document.createElement('div');c.className='scout-composer';c.innerHTML='<form class="scout-form" data-scout-form><label class="sr-only" for="scoutV4Input">Tell Scout what you need</label><input id="scoutV4Input" class="scout-input" type="search" autocomplete="off" placeholder="e.g. 65-inch TV under A$2,000 for a bright room"><button class="scout-send" type="submit" aria-label="Ask Scout"><span aria-hidden="true">↑</span></button></form><p class="scout-helper">Try natural language: <span>“no Samsung”</span> · <span>“battery matters more”</span> · <span>“must have USB-C”</span></p>';panel.insertBefore(c,foot||null);}
function canonicalStateQuery(){const s=state.decisionState||{},a=[];(s.hardConstraints?.requiredTags||[]).forEach(x=>a.push('must have '+x.split('-').join(' ')));(s.hardConstraints?.excludedTags||[]).forEach(x=>a.push('without '+x.split('-').join(' ')));(s.hardConstraints?.excludedBrands||[]).forEach(x=>a.push('no '+x));(s.softPreferences||[]).forEach(x=>a.push((x.priority==='highest'?'top priority ':x.priority==='high'?'priority ':'')+String(x.tag||'').split('-').join(' ')));(s.softExclusions||[]).forEach(x=>a.push('avoid '+String(x).split('-').join(' ')));for(const c of s.numericConstraints||[]){const lead=c.mode==='min'?'at least ':c.mode==='max'?'at most ':c.mode==='exact'?'exactly ':'around ';a.push(lead+c.value+(c.unit==='in'?' inches':' '+c.unit));}const ci=s.categoryIntent||{};if(ci.workflow)a.push(ci.workflow+' workflow');if(ci.beanSwitch)a.push('switch beans');if(ci.cold)a.push('cold coffee');if(ci.compact)a.push('compact');if(s.brandPreference)a.push('prefer '+s.brandPreference);return [...new Set(a)].join(' ');}
function firstNumber(text){const compact=String(text||'').split(',').join(' '),parts=compact.split(' ');for(const part of parts){const n=Number(part.replace('$',''));if(Number.isFinite(n)&&n>0)return n;}return 0;}
function includesAny(text,terms){return terms.some(x=>text.includes(x));}
function resolveFollowUp(t){const n=String(t||'').toLowerCase(),number=firstNumber(n);let display=t,query=t;if(number&&includesAny(n,['another','extra'])){const base=state.budget||Number(state.last?.results?.[0]?.priceBasis)||0;if(base){state.budget=base+number;query='maximum budget $'+state.budget;display=t+' (new ceiling A$'+fmt(state.budget)+')';}}else if(number&&includesAny(n,['budget','spend','under','maximum','max ','ceiling'])){state.budget=number;query='maximum budget $'+number;}else if(includesAny(n,['cheaper','lower budget','spend less','less expensive'])){const base=state.budget||Number(state.last?.results?.[0]?.priceBasis)||0;if(base){state.budget=Math.max(50,Math.floor(base*.8/10)*10);query='maximum budget $'+state.budget+' value is a high priority';display='Find something cheaper (new ceiling A$'+fmt(state.budget)+')';}else query='value and lower price are my highest priorities';}else if(includesAny(n,['no budget','ignore budget','remove budget'])){state.budget=null;if(state.decisionState){state.decisionState.budget=null;if(state.decisionState.hardConstraints)state.decisionState.hardConstraints.budgetCeiling=null;}query='budget is not a constraint';}else if(includesAny(n,['more premium','premium option','higher end','high end'])){query='premium is my highest priority';}else if(includesAny(n,['no brand preference','any brand','ignore brand'])){if(state.decisionState)state.decisionState.brandPreference=null;query='no brand preference';}return {display,query};}
function chips(d){const s=d.decisionState||{},a=[];if(d.interpretation?.category)a.push(d.interpretation.category);else if(s.category)a.push(human(s.category));if(s.budget?.amount)a.push((s.budget.hard?'Up to ':'Around ')+'A$'+fmt(s.budget.amount));(s.hardConstraints?.requiredTags||[]).forEach(x=>a.push('Must have '+human(x)));(s.hardConstraints?.excludedBrands||[]).forEach(x=>a.push('No '+x));(s.softPreferences||[]).filter(x=>x.priority==='high'||x.priority==='highest').forEach(x=>a.push(human(x.tag)+' matters most'));return a.length?'<div class="scout-brief"><div class="scout-brief-head"><strong>Your brief</strong><span>I’ll keep these in mind</span></div><div class="scout-state">'+a.slice(0,7).map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></div>':'';}
function thinking(on){thread().querySelector('.scout-thinking')?.remove();if(on){const d=document.createElement('div');d.className='scout-thinking';d.innerHTML='<span class="scout-thinking-orb" aria-hidden="true"></span><span>Scout is matching your priorities</span><span class="scout-dots" aria-hidden="true"><i></i><i></i><i></i></span>';thread().appendChild(d);body.setAttribute('aria-busy','true');body.scrollTop=body.scrollHeight;}else body.removeAttribute('aria-busy');}
function evidenceLabel(c){const l=String(c?.label||'').toLowerCase();return l.includes('high')?'Strong evidence':l.includes('moderate')?'Good evidence':'Check details';}
function rankLabel(i,r){if(r.hardConstraintStatus==='unverified')return 'Needs checking';if(r.hardConstraintStatus==='ineligible')return 'Closest option';return i===0?'Best fit':i===1?'Strong alternative':'Another option';}
function placeholder(r){const words=String(r.category||'APG').split(' ').filter(Boolean),label=words.map(x=>x.charAt(0)).join('').slice(0,2).toUpperCase();return '<div class="scout-card-media scout-card-placeholder" aria-hidden="true"><span>'+esc(label||'APG')+'</span></div>';}
function friendlyReason(s){let x=String(s||'');[['hard constraint','must-have'],['hard requirement','must-have'],['Deep maintained evidence','Stronger APG research coverage'],['Known maintained price basis','APG reference price'],['maintained evidence','APG research'],['fit signal','match signal'],['budget compliance','whether it stays within budget'],['unverified','not yet verified']].forEach(([a,b])=>{x=x.split(a).join(b);x=x.split(a.charAt(0).toUpperCase()+a.slice(1)).join(b);});return x;}
function resultCard(r,i){const reasons=(r.reasons||[]).slice(0,3).map(friendlyReason),watch=friendlyReason((r.verificationNeeds||[])[0]||r.tradeoff||(r.gaps||[])[0]||''),price=Number(r.priceBasis)>0?'<span class="scout-price">Reference A$'+fmt(r.priceBasis)+'</span>':'';return '<article class="scout-card'+(i===0?' is-top':'')+'"><div class="scout-card-shell">'+placeholder(r)+'<div class="scout-card-main"><div class="scout-card-top"><div><span class="scout-rank">'+esc(rankLabel(i,r))+'</span><span class="scout-brand">'+esc(r.brand)+'</span><h4>'+esc(r.name)+'</h4></div><span class="scout-confidence">'+esc(evidenceLabel(r.confidence))+'</span></div><div class="scout-card-meta">'+price+'<span>'+esc(r.match||'Fit assessed')+'</span></div>'+(reasons.length?'<div class="scout-why"><strong>Why it fits</strong><ul>'+reasons.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>':'')+(watch?'<div class="scout-watch"><strong>'+(r.verificationNeeds?.length?'Check before buying':'Trade-off')+'</strong><span>'+esc(watch)+'</span></div>':'')+'<a class="scout-card-link" href="'+esc(r.url)+'">View product research <span aria-hidden="true">→</span></a></div></div></article>';}
function render(d){const rs=(d.results||[]).slice(0,3);let h=chips(d);if(d.audit?.hardConstraintFallback)h+=bot('<strong>I can’t verify a clean match for every must-have yet.</strong><span class="scout-intro">I’m showing the closest options and clearly marking what still needs checking.</span>');if(!rs.length)return h+bot('<strong>I don’t have a reliable match from APG’s current coverage.</strong><span class="scout-intro">Try relaxing one requirement or naming the product category more broadly.</span>');h+=bot('<strong>I found the strongest matches for your brief.</strong><span class="scout-intro">The order reflects fit to what you told me — not star ratings or sponsorship.</span>')+'<div class="scout-results">'+rs.map(resultCard).join('')+'</div>';const rec=d.recommendation;if(rec)h+='<section class="scout-explain"><span class="scout-explain-kicker">Scout’s take</span><strong>Why the first option leads</strong><p>'+esc(friendlyReason((rec.whyItWon||[])[0]||'It best matches the needs you have given me so far.'))+'</p><details><summary>What could change the answer?</summary><p>'+esc(friendlyReason((rec.whenTheAnswerWouldChange||[])[0]||'A different must-have, budget or top priority could change the leading fit.'))+'</p></details></section>';const slugs=rs.map(r=>r.slug),actions=[];if(slugs.length>1)actions.push('<a class="scout-action primary" href="/compare/custom/?products='+slugs.join(',')+'">Compare top matches</a>');actions.push('<button class="scout-action" type="button" data-scout-follow="cheaper">Lower the price</button>');actions.push('<button class="scout-action" type="button" data-scout-follow="more premium">More premium</button>');if(state.budget)actions.push('<button class="scout-action" type="button" data-scout-follow="remove budget">Remove budget</button>');actions.push('<a class="scout-action quiet" href="/decision-lab/?q='+encodeURIComponent(canonicalStateQuery())+(state.budget?'&budget='+state.budget:'')+(state.category?'&category='+encodeURIComponent(state.category):'')+'">Open full decision view</a>');actions.push('<button class="scout-action quiet" type="button" data-scout-reset>Start over</button>');h+='<div class="scout-actions">'+actions.join('')+'</div><p class="scout-refine">Want a better answer? Tell me what you disliked about these options, a brand to avoid, or the one feature that matters most.</p>';return h;}
function update(d){state.last=d;state.decisionState=d.decisionState||null;state.budget=d.decisionState?.budget?.amount?Number(d.decisionState.budget.amount):null;state.category=d.decisionState?.category||state.category||null;}
async function ask(text,forcedCategory){text=String(text||'').trim();if(!text||state.busy)return;if(forcedCategory)state.category=forcedCategory;const r=resolveFollowUp(text);thread().insertAdjacentHTML('beforeend',user(r.display));state.busy=true;thinking(true);const input=panel.querySelector('.scout-input'),send=panel.querySelector('.scout-send');if(input)input.disabled=true;if(send)send.disabled=true;try{const prior=canonicalStateQuery(),q=[r.query,prior].filter(Boolean).join(' '),p=new URLSearchParams({q});if(state.budget)p.set('budget',String(state.budget));if(state.category)p.set('category',state.category);const res=await fetch('/api/decision?'+p,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('decision');const d=await res.json();update(d);thinking(false);thread().insertAdjacentHTML('beforeend',render(d));body.scrollTop=body.scrollHeight;}catch(e){thinking(false);thread().insertAdjacentHTML('beforeend',bot('<strong>I couldn’t reach the matcher just now.</strong><span class="scout-intro">You can still use APG search, category pages and the full decision view.</span>'));}finally{state.busy=false;if(input)input.disabled=false;if(send)send.disabled=false;input?.focus();}}
let backdrop=document.querySelector('.scout-backdrop');if(!backdrop){backdrop=document.createElement('button');backdrop.type='button';backdrop.className='scout-backdrop';backdrop.setAttribute('aria-label','Close Scout');backdrop.hidden=true;document.body.appendChild(backdrop);}
function open(v){panel.hidden=!v;backdrop.hidden=!v;launcher.setAttribute('aria-expanded',String(v));document.body.classList.toggle('scout-open',v);if(v){if(!body.querySelector('.scout-thread'))welcome();ensureComposer();setTimeout(()=>panel.querySelector('.scout-input')?.focus(),50);}else launcher.focus();}
launcher.addEventListener('click',()=>open(panel.hidden));backdrop.addEventListener('click',()=>open(false));panel.querySelector('[data-apg-assistant-close]')?.addEventListener('click',()=>open(false));document.addEventListener('submit',e=>{const f=e.target.closest('[data-scout-form]');if(!f)return;e.preventDefault();const i=f.querySelector('.scout-input'),v=i.value;i.value='';ask(v);});body.addEventListener('click',e=>{const q=e.target.closest('[data-scout-q]');if(q)ask(q.dataset.scoutQ,q.dataset.scoutCategory||null);const f=e.target.closest('[data-scout-follow]');if(f)ask(f.dataset.scoutFollow);if(e.target.closest('[data-scout-reset]')){welcome();panel.querySelector('.scout-input')?.focus();}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)open(false);});
})();`;
module.exports={js};
