const js=`(()=>{
const launcher=document.getElementById('apgAssistantLauncher'),panel=document.getElementById('apgAssistantPanel'),body=document.getElementById('apgAssistantBody');if(!launcher||!panel||!body)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number(n||0).toLocaleString('en-AU');
const state={busy:false,last:null,decisionState:null,budget:null,category:null};
const brand=panel.querySelector('.apg-assistant-brand');if(brand)brand.querySelector('span:last-child')?.replaceChildren();if(brand){const copy=brand.querySelector('span:last-child');if(copy)copy.innerHTML='<strong>Scout · APG decision guide</strong><small>Decision Engine v4 · governed state</small>';}
const foot=panel.querySelector('.apg-assistant-foot');if(foot)foot.innerHTML='<strong>Scout uses maintained APG evidence and explicit constraints.</strong> Retailer commission contributes zero recommendation points.';
function bot(t){return '<div class="scout-row"><div class="scout-bubble">'+t+'</div></div>'}function user(t){return '<div class="scout-row user"><div class="scout-bubble">'+esc(t)+'</div></div>'}
function thread(){let t=body.querySelector('.scout-thread');if(!t){body.innerHTML='<div class="scout-thread"></div>';t=body.querySelector('.scout-thread')}return t;}
function welcome(){state.last=null;state.decisionState=null;state.budget=null;state.category=null;body.innerHTML='<div class="scout-thread">'+bot('Hi, I’m <strong>Scout</strong>. Tell me what you’re buying, your maximum budget, priorities and any deal-breakers. I’ll keep those as structured decision state and explain why the answer changes.')+'<div class="scout-start"><strong>Try a buying situation</strong><div class="scout-chips"><button class="scout-chip" data-scout-q="75-inch TV for a bright living room, sport and Netflix under $2500">TV for a bright room</button><button class="scout-chip" data-scout-q="robot vacuum for pet hair and mopping">Robot vacuum for pets</button><button class="scout-chip" data-scout-q="coffee machine for flat whites under $1300">Coffee machine</button></div></div></div>';}
function ensureComposer(){if(panel.querySelector('.scout-composer'))return;const c=document.createElement('div');c.className='scout-composer';c.innerHTML='<form class="scout-form" data-scout-form><label class="sr-only" for="scoutV4Input">Tell Scout what you need</label><input id="scoutV4Input" class="scout-input" type="search" autocomplete="off" placeholder="e.g. no Samsung; battery matters more"><button class="scout-send" type="submit" aria-label="Ask Scout">→</button></form><p class="scout-helper"><strong>Refine naturally:</strong> “cheaper”, “no Samsung”, “battery matters more”, or “I can spend another $500”.</p>';panel.insertBefore(c,foot||null);}
function canonicalStateQuery(){const s=state.decisionState||{},a=[];(s.hardConstraints?.requiredTags||[]).forEach(x=>a.push('must have '+x.replace(/-/g,' ')));(s.hardConstraints?.excludedTags||[]).forEach(x=>a.push('without '+x.replace(/-/g,' ')));(s.hardConstraints?.excludedBrands||[]).forEach(x=>a.push('no '+x));(s.softPreferences||[]).forEach(x=>a.push((x.priority==='highest'?'top priority ':x.priority==='high'?'priority ':'')+String(x.tag||'').replace(/-/g,' ')));(s.softExclusions||[]).forEach(x=>a.push('avoid '+String(x).replace(/-/g,' ')));for(const c of s.numericConstraints||[]){const lead=c.mode==='min'?'at least ':c.mode==='max'?'at most ':c.mode==='exact'?'exactly ':'around ';a.push(lead+c.value+(c.unit==='in'?' inches':' '+c.unit));}const ci=s.categoryIntent||{};if(ci.workflow)a.push(ci.workflow+' workflow');if(ci.beanSwitch)a.push('switch beans');if(ci.cold)a.push('cold coffee');if(ci.compact)a.push('compact');if(s.brandPreference)a.push('prefer '+s.brandPreference);return [...new Set(a)].join(' ');}
function resolveFollowUp(t){const n=String(t||'').toLowerCase(),m=n.match(/[0-9][0-9,]*/),number=m?Number(m[0].replace(/,/g,'')):0;let display=t,query=t;if(number&&(n.includes('another')||n.includes('extra'))){const base=state.budget||Number(state.last?.results?.[0]?.priceBasis)||0;if(base){state.budget=base+number;query='maximum budget $'+state.budget;display=t+' (new ceiling A$'+fmt(state.budget)+')';}}else if(number&&(/budget|spend|under|maximum|max |ceiling/.test(n))){state.budget=number;query='maximum budget $'+number;}else if(/cheaper|lower budget|spend less|less expensive/.test(n)){const base=state.budget||Number(state.last?.results?.[0]?.priceBasis)||0;if(base){state.budget=Math.max(50,Math.floor(base*.8/10)*10);query='maximum budget $'+state.budget+' value is a high priority';display='Find something cheaper (new ceiling A$'+fmt(state.budget)+')';}else query='value and lower price are my highest priorities';}else if(/no budget|ignore budget|remove budget/.test(n)){state.budget=null;if(state.decisionState){state.decisionState.budget=null;if(state.decisionState.hardConstraints)state.decisionState.hardConstraints.budgetCeiling=null;}query='budget is not a constraint';}return {display,query};}
function chips(d){const s=d.decisionState||{},a=[];if(s.category)a.push(s.category.replace(/-/g,' '));if(s.budget?.amount)a.push((s.budget.hard?'max ':'around ')+'A$'+fmt(s.budget.amount));(s.hardConstraints?.requiredTags||[]).forEach(x=>a.push('must '+x.replace(/-/g,' ')));(s.hardConstraints?.excludedBrands||[]).forEach(x=>a.push('no '+x));return a.length?'<div class="scout-state">'+a.slice(0,7).map(x=>'<span>'+esc(x)+'</span>').join('')+'</div>':'';}
function render(d){const rs=(d.results||[]).slice(0,3);let h=chips(d);if(d.audit?.hardConstraintFallback)h+=bot('I can’t verify an option that cleanly satisfies every hard constraint from the maintained data. Closest candidates are shown as conflicts or verification gaps — not as clean matches.');if(!rs.length)return h+bot('I don’t have a maintained candidate for that yet. Try relaxing one constraint or browse the category coverage.');h+=bot('These are the strongest current fits. <strong>Fit is not a review score.</strong>')+'<div class="scout-results">'+rs.map(r=>'<article class="scout-card"><div class="scout-card-top"><div><span class="scout-brand">'+esc(r.brand)+'</span><h4>'+esc(r.name)+'</h4></div><div class="scout-badges"><span class="scout-match">'+esc(r.match)+'</span><span class="scout-confidence">'+esc(r.confidence?.label||'Evidence checked')+'</span></div></div>'+(r.reasons?.length?'<ul>'+r.reasons.slice(0,3).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'')+(r.verificationNeeds?.length?'<p class="scout-watch"><strong>Verify:</strong> '+esc(r.verificationNeeds[0])+'</p>':r.tradeoff?'<p class="scout-watch"><strong>Compromise:</strong> '+esc(r.tradeoff)+'</p>':'')+'<a href="'+esc(r.url)+'">Inspect product evidence →</a></article>').join('')+'</div>';const rec=d.recommendation;if(rec)h+='<div class="scout-explain"><strong>Why this leads</strong>'+esc((rec.whyItWon||[])[0]||'It best matches the current maintained decision state.')+'<br><strong style="margin-top:6px">When the answer changes</strong>'+esc((rec.whenTheAnswerWouldChange||[])[0]||'A new hard constraint or priority could change it.')+'</div>';const slugs=rs.map(r=>r.slug);h+='<div class="scout-actions">'+(slugs.length>1?'<a class="scout-action primary" href="/compare/custom/?products='+slugs.join(',')+'">Compare these</a>':'')+'<a class="scout-action" href="/decision-lab/?q='+encodeURIComponent(canonicalStateQuery())+(state.budget?'&budget='+state.budget:'')+(state.category?'&category='+encodeURIComponent(state.category):'')+'">Open Decision Lab</a><button class="scout-action" data-scout-follow="cheaper">Find something cheaper</button><button class="scout-action" data-scout-reset>Start over</button></div>';return h;}
function update(d){state.last=d;state.decisionState=d.decisionState||null;state.budget=d.decisionState?.budget?.amount?Number(d.decisionState.budget.amount):null;state.category=d.decisionState?.category||null;}
async function ask(text){text=String(text||'').trim();if(!text||state.busy)return;const r=resolveFollowUp(text);thread().insertAdjacentHTML('beforeend',user(r.display));state.busy=true;try{const prior=canonicalStateQuery(),q=[r.query,prior].filter(Boolean).join(' '),p=new URLSearchParams({q});if(state.budget)p.set('budget',String(state.budget));if(state.category)p.set('category',state.category);const res=await fetch('/api/decision?'+p,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('decision');const d=await res.json();update(d);thread().insertAdjacentHTML('beforeend',render(d));body.scrollTop=body.scrollHeight;}catch(e){thread().insertAdjacentHTML('beforeend',bot('The decision service is temporarily unavailable. Decision Lab and maintained category pages are still available.'));}finally{state.busy=false;}}
function open(v){panel.hidden=!v;launcher.setAttribute('aria-expanded',String(v));if(v){if(!body.querySelector('.scout-thread'))welcome();ensureComposer();setTimeout(()=>panel.querySelector('.scout-input')?.focus(),50);}else launcher.focus();}
launcher.addEventListener('click',()=>open(panel.hidden));panel.querySelector('[data-apg-assistant-close]')?.addEventListener('click',()=>open(false));document.addEventListener('submit',e=>{const f=e.target.closest('[data-scout-form]');if(!f)return;e.preventDefault();const i=f.querySelector('.scout-input'),v=i.value;i.value='';ask(v);});body.addEventListener('click',e=>{const q=e.target.closest('[data-scout-q]');if(q)ask(q.dataset.scoutQ);const f=e.target.closest('[data-scout-follow]');if(f)ask(f.dataset.scoutFollow);if(e.target.closest('[data-scout-reset]'))welcome();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)open(false);});
})();`;
module.exports={js};
