create table public.apg_retailer_observations (
  id bigint generated by default as identity primary key,
  product_slug text not null,
  retailer text not null,
  retailer_url text not null,
  listing_id text,
  price_aud numeric(12,2),
  availability text,
  source_mechanism text not null,
  confidence text not null check (confidence in ('low','medium','high','verified')),
  observed_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.apg_retailer_observations enable row level security;
revoke all on public.apg_retailer_observations from anon, authenticated;

create index apg_retailer_observations_product_time_idx on public.apg_retailer_observations (product_slug, observed_at desc);
create index apg_retailer_observations_retailer_time_idx on public.apg_retailer_observations (retailer, observed_at desc);

create table public.apg_price_alert_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_slug text not null,
  retailer_scope text not null default 'eligible_non_amazon',
  target_price_aud numeric(12,2),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_slug, retailer_scope)
);

alter table public.apg_price_alert_preferences enable row level security;
create policy "alerts_select_own" on public.apg_price_alert_preferences for select to authenticated using ((select auth.uid()) = user_id);
create policy "alerts_insert_own" on public.apg_price_alert_preferences for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "alerts_update_own" on public.apg_price_alert_preferences for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "alerts_delete_own" on public.apg_price_alert_preferences for delete to authenticated using ((select auth.uid()) = user_id);

create trigger apg_price_alert_preferences_set_updated_at
before update on public.apg_price_alert_preferences
for each row execute function public.apg_set_updated_at();